### ISSUE TITLE
When using `print(arg1, arg2)` the output shows up on separate lines

### ISSUE THREAD

**Issue by moshez** [pyscript/pyscript#103]
This is an inconsistency from the behavior of the regular Python interpreter.
For example, in a regular Python interpreter, this will be the result of
`print("Hello", "world")`:

<img width="258" alt="Screen Shot 2022-05-01 at 13 35 31" src="https://user-images.githubusercontent.com/422703/166161808-2ed2a55a-a9fc-4552-bdf0-b9bceb8c734f.png">

The following is the equivalent using `pyscript`:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <title>PyScript Hello World</title>

    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="stylesheet" href="https://pyscript.net/unstable/pyscript.css" />
    
    <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
  </head>

  <body>
    <py-env>
    </py-env>
    <py-script output="out">
print("Hello", "world")
    </py-script>
    <div id="out"></div>
  </body>
</html>
```

This shows up in the HTML as:

<img width="76" alt="Screen Shot 2022-05-01 at 13 32 08" src="https://user-images.githubusercontent.com/422703/166161758-1f41f682-a150-423b-873a-2d0cfeafe8e4.png">

This is because every argument is output to a separate `div` element in the HTML:

<img width="725" alt="Screen Shot 2022-05-01 at 13 32 57" src="https://user-images.githubusercontent.com/422703/166161759-fb4bf4d5-c049-4741-8ec8-bb2d00c1654e.png">

This will make Python output from code that expects it to be compact to spread out across multiple lines.

Thanks to @khorn for his help with coming up with a reproducible example and writing it up.

**Comment by JeffersGlass** [comment]
There's probably a design decision to be made here - how should PyScript handle arbitrary output to stdout? - Since [Python's print function](https://github.com/mozillazg/pypy/blob/1cb1c9de8cf0e9d33507273ec1562fd1df11ab1a/pypy/module/__builtin__/app_io.py#L87-L132) makes one write call to stdout _per positional argument:_

```
def print_(*args, **kwargs):
    fp = kwargs.pop("file", None)
    if fp is None:
        fp = sys.stdout

    .... code for handling unicode, seperates, and line ends omitted ...

    for i, arg in enumerate(args):
        if i:
            write(sep)
        write(arg)
    write(end)
```


Right now, [each write to stdout calls to PyScript.write](https://github.com/pyscript/pyscript/blob/442af7bd97095e67df9dd2173e5997cb467a5d2b/pyscriptjs/src/interpreter.ts#L388-L393), and PyScript.write [by default creates a new div per call](https://github.com/pyscript/pyscript/blob/442af7bd97095e67df9dd2173e5997cb467a5d2b/pyscriptjs/src/pyscript.py#L101-L111) (when its append argument is True).

Some possible solutions, off the top of my head (there are probably better ones):

- Only create one PyScript-created-div per element_id in the DOM; first PyScript.write call creates this div and writes to it, future calls with the same element ID append to this div. Possibly replacing carriage returns/newlines with &lt;br&gt; tags?
- Make PyScript.write() stateful, and only start a new div if stdout passes a newline/carriage return.
- Accept that each call to stdout creates a new div, and document this for users.

Hope I'm not stepping on toes here, just interested in and excited about this project.

**Comment by fpliger** [comment]
thanks for reporting @moshez  and @JeffersGlass  for trying to figure out the underlying issue. That's correct, there are some opinionated design choices that are causing the issue. In reality, this is a bug and the design we want to implement should allow users to configure how they actually would like this to behave. (For instance, appending vs overwriting to an output div). 

This is related to #76 but shouldn't be a duplicate.
