### ISSUE TITLE
I think PyScript should come out with an IDE plugin first to make coding easy.

### ISSUE THREAD

**Issue by ChinaGodzilla** [pyscript/pyscript#1051]
At present, I use pycharm to open the html document for editing, and then write python code in it. The efficiency is very low, because the code needs to be completely manually entered, and the IDE will not prompt or complete any PYTHON code. As shown in the picture below, I try to only enter 'import' and can only enter it manually.

![image](https://user-images.githubusercontent.com/43966525/207842951-daac8a3a-558e-4b1d-9ff4-642cc1a9cf83.png)

**Comment by Mr-MaNia7** [comment]
This is an elegant idea!

**Comment by marimeireles** [comment]
Yes!
I've been thinking about this too.
In reality the recommended way to develop pyscript is by using multiple files, so instead of developing on the HTML you dev. in python files and import them.
However this is a very valid request.
I know we have an extension to vscode, but doesn't seem to do autocomplete: https://betterprogramming.pub/pyscript-run-python-with-html-e77f1786a062
I don't think it's currently on the backlog as we'll have to figure out individual solutions for each IDE and I don't think anyone in the team has expertise on that. But community contributions are very welcome ❤️
I'll try to have a look on it at some point these holidays.
Cheers!

**Comment by ChinaGodzilla** [comment]
@marimeireles  

I am very optimistic about this project! He is so nice. Many PYTHON users will gain a wider market.

At the same time, I saw many projects that PYTHON supports WEB development. They have a similar problem with pyscript, that is, the so-called "PYTHON coding" is actually extremely difficult, and must be separated from the smart IDE, almost pure text command line coding, many people see here decisively give up research.

But without the support of intelligent IDEs such as pycharm, few people can write huge modules and products only by command line (for example, if javascript does not have the support of those intelligent IDEs, how many people can use plain text coding to pile up huge modules) , this Proposals will greatly increase the enthusiasm of new users for this project. When writing code is easy, more people will enter the project, making the project colorful.

Cheers!

**Comment by ChinaGodzilla** [comment]
In the end, I found that PYCHARM Professional Edition supports the functions I talked about.

**Comment by ChinaGodzilla** [comment]
![image](https://user-images.githubusercontent.com/43966525/218271519-6bbd311d-858a-409e-926b-d34862178b85.png)

**Comment by FabioRosado** [comment]
Nice find @ChinaGodzilla !

Another solution that doesn't require the Professional Edition is creating a python file and then use it in your `py-script` tag. That way you can write your python code and any IDE should be able to auto complete since it's not seeing the file as HTML. 

For example, let's assume that you write your python code in a file called `my_code.py` you can do:

```html
<py-script src="./my_code.py">
</py-script>
```



```

**Comment by ChinaGodzilla** [comment]
@FabioRosado THANKS for your time!

**Comment by FabioRosado** [comment]
No worries! Since we found a way to address this, are you happy if we close the issue? 😄

**Comment by ChinaGodzilla** [comment]
@FabioRosado  OK
