### ISSUE TITLE
REPL Output does not show up OR it shows in random places

### ISSUE THREAD

**Issue by limitcracker** [pyscript/pyscript#1070]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I used the following code in my blog:

```
<py-repl id="my-repl-24dec22-0839" auto-generate="true"> 
a = 15
b = 2
print(a + b) 
print(a - b)
</py-repl>
```

And although it runs I don't get output. Instead I get this:
![image](https://user-images.githubusercontent.com/544391/209449221-36ed4890-74dd-40c9-9600-daad95a56c3f.png)

Here is the page that the problem occurs:
https://giftakis.gr/programmatismos-python/programmatismos-arxarioi/domi-akolouthias-python/ergastirio-metavlites-python

On a Codepen example it works though:
https://codesandbox.io/s/pyscript-education-o9pm05?file=/index.html

Any ideas?

____
Br, John

**Comment by FabioRosado** [comment]
Hello @limitcracker  thank you for raising this issue.

Can I check with you, are the ids of each py-repl distinct from one another? 🤔 

Also, since the last release, when you print things they will show up in a py-terminal which by default is attached to the end of the page. Although it seems Notion might be doing something and is messing up the render of the py-terminal.

Jeff has a WIP PR (#1063) that I think will fix this issue for you.  Currently, you can use the [`display`API](https://docs.pyscript.net/latest/reference/API/display.html)  to have the output under the py-repl. 

I'm not sure if using `display` explicitly will mess your use case. But if it does, you could monkeypatch print to use display under the hood. Something like this *should* work:

```html
<py-script>
print = display
</py-scirpt>
```

Let me know if this helps 😄

**Comment by limitcracker** [comment]
Hi @FabioRosado ! Yes the monkeypatch worked :)
I tested it in a page with multiple `<py-repl>` tags also. 
I 'll be waiting for the fix also.

One more thing is `py-onClick` to be replaced by `py-click`?

**Comment by FabioRosado** [comment]
That's great news!

Yes, `pys-onClick` is deprecated and will be removed soon. Using `py-click="func()"` is the recommended way to handle click events now 😄
