### ISSUE TITLE
Offer different options to catch user input (console, window prompt, others?)

### ISSUE THREAD

**Issue by limitcracker** [pyscript/pyscript#1080]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

A way to ask for input from the user in loops. Alternative to the built in browser pop up that now stands.

i.e.

```
sum = 0
x = int( input("Give number:) )
while sum < 100:
    sum += x
print(suma)
```

### Why is this needed

Builtin browser pop up is not good.

**Comment by marimeireles** [comment]
Sorry, I'm not sure if I get it.
You'd like to get user input in the webpage rather than having a window to pop-up?
It seems like https://github.com/pyodide/pyodide/pull/1728 allows us to overwrite the default `prompt` function.
I'm not sure how to redirect this to and HTML tag though, in case that's your request. But I guess that's a reasonable request. For future reference, this is probably the relevant entry point that we have to modify: https://github.com/pyscript/pyscript/blob/bb5c59307a4f18f8d0a85ee379274008f15afb7e/pyscriptjs/src/pyodide.ts#L59-L69

**Comment by marimeireles** [comment]
Okay, I thought on a much easier solution:
You can just capture the value of an `<input>` or literally any other HTML tag and pass that to your Python code. I guess that's a much easier acceptable way of dealing with this problem?
We could also have different defaults, maybe default to the terminal... (can't think of any other use case). Still relevant, but not super high priority, imo.

**Comment by hoodmane** [comment]
This requires syncio so it can only be implemented when Pyodide runs in a worker. It should be possible to set up input devices to read from each of these places (`/dev/prompt`, `/dev/pyterminal`, etc). Though pyterminal should likely be a tty.

**Comment by WebReflection** [comment]
This is fixed in current PyScript when workers are used, without ever blocking the main UI.
