### ISSUE TITLE
API for users to edit py-config tag?

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#1102]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

Should we support an API for users of a webpage that contains pyscript to be able to modify the content of pyconfig (permanently in their own browser contexts? we do that with cookies and download things over again? with the browserDB thing? idk!)

**Comment by WebReflection** [comment]
modify and permanently don't cope well with each other so I think we can close this, specially because the config topic is either you have one for the main thread that covers your bootstrap, or you are free to implement your extra imports or dependencies later on within your code.

Side effecting the config to all main scripts doesn't look like the best we can offer, so I am closing this as currently not in our radar, happy to discuss this further as *discussion* instead of issue though ... after all , there is where we have the **proposal** option.
