### ISSUE TITLE
Fix the xfail tests in test_stdio_handling.py

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1314]
This is a follow-up of https://github.com/pyscript/pyscript/pull/1258.
Original discussion: https://github.com/pyscript/pyscript/pull/1258/files#r1149405704

These two tests were temporarily skipped to make it possible to merge the PR earlier, but they should now be fixed ASAP.

**Comment by JeffersGlass** [comment]
Looking at `test_targeted_stdio_async`, it seems that some of the await-all-the-things that happened in the synclink PR have caused the `output` attribute to "work" in Python coroutines. The test should output nothing except "DONE" to the body of the page, but now "two" and "three" are also appearing:

![image](https://user-images.githubusercontent.com/1931111/228044903-b53f8af8-77b6-4048-86f8-a41ca66296a4.png)

"Work" there is in heavy quotes, because of course this is an unplanned for change. I would be delighted if this attribute worked in coroutines, but that would require us what's actually happening here, and not just getting lucky. More investigation is due.

**Comment by JeffersGlass** [comment]
Looking back on my process for writing that test in #1063, it (and the TargetedStdio concept in general) relied on its `beforePyReplExec()` and `afterPyReplExec()` hooks being called synchronously with the `pyExec` call; now that any or all of those three calls can be async, the concept  may need to be rethought.

**Comment by hoodmane** [comment]
@JeffersGlass I think we need to fix `test_asyncio.py` first. I am pretty confident about what the fix for that looks like and it involves fixes the execution order. I think it will force this test to fail properly again as a side-effect.
