### ISSUE TITLE
SSL module not available error when trying to connect to HTTPS URL

### ISSUE THREAD

**Issue by Harshu1441** [pyscript/pyscript#1321]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When trying to fetch an image from google or S3 bucket using PIL library trough pyscript , I received the following error: "Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available." 

**Expected behavior**
I expected to fetch the image an see the output without encountering an error.

**Actual behavior**
I encountered the "Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available" error.

**System information**
- Operating system: Windows 10
- Python version: 3.10
- Browser : Version 111.0.1 (64 bit)

### What browsers are you seeing the problem on? (if applicable)

Firefox

### Console info

```shell
(Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")
```

**Comment by JeffersGlass** [comment]
The ssl module is one of the modules in the standard library that is [unvendored by Pyodide](https://pyodide.org/en/stable/usage/wasm-constraints.html#optional-modules), to reduce the initial download size of the runtime. If you are using PyScript 2022.09.1 or newer, you can include this in your project using:
```html
<py-config>
    packages = ['ssl']
</py-config>
```
However, just because this will allow the ssl module to be imported does not mean that all of its functionality actually works within the browser. See, for instance, the discussion in [this Issue in the Pyodide repo](https://github.com/pyodide/pyodide/issues/2884), and in particular this comment from tiran (applies to both the smptlib he's disucssing and ssl):
> Browser environment only support asynchronous, non-blocking sockets. You also can't connect to arbitrary ports from a browser. You would need a helper process on the server side to emulate TCP sockets over WebSockets, see https://emscripten.org/docs/porting/networking.html
