### ISSUE TITLE
Fix indentation mismatch

### ISSUE THREAD

**Issue by amgawishx** [pyscript/pyscript#136]
Lots of the tags doesn't work properly until adjusted for indentation, for example:
```html
   <py-env>
         - matplotlib
         - numpy
   </py-env>
```
Won't work until adjusted the indentation like the following: 
```html
   <py-env>
- matplotlib
- numpy
   </py-env>
```
Which makes for a slightly harder to read code. Same goes with the `<py-script>` tag too.

**Comment by Rjtsahu** [comment]
Since python understands _indentation_ (and not braces), I would say this is something dev have to make sure of (as if they do while writing normal python scripts ).

While it would be great if IDEs provide highlighting support for python code in HTML.

**Comment by antocuni** [comment]
Actually, this is unrelated to the fact that Python is sensitive to indentation.
I *think* this is the code which parses the content of `py-env` as yaml:
https://github.com/pyscript/pyscript/blob/b7d748c96a6f54d4a82f33f1b2e1c749a4e1b99e/pyscriptjs/src/components/pyenv.ts#L38

AFAIK yaml files needs to start from column 0, that's why the indentation inside `<py-env>` is a problem. But in theory, we could (and probably should) remove all the extra indentation in a similar way to what python's `textwrap.dedent` does.
@fpliger what do you think?

**Comment by fpliger** [comment]
Yeah, this is a bug. I think it has been addressed in main already (by https://github.com/pyscript/pyscript/pull/130) but it's worth testing.
