### ISSUE TITLE
<py-repl> should use Shadow DOM instead

### ISSUE THREAD

**Issue by WebReflection** [pyscript/pyscript#1445]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

There are surrounding circumstances where generic CSS rules can affect the `<py-repl>` look and feel, if not its visual behavior. We are currently using a global style to address `.py-repl` internals and `py-repl` itself but if we want this component to survive in the wild we should consider isolating its style within a Shadow DOM root node.

### Additional Context

This has been noticed while embedding a `<py-repl>` in [reveal.js](https://revealjs.com/)

**Comment by WebReflection** [comment]
MR https://github.com/pyscript/pyscript/pull/1449 seems to address *most* pain points around the repl editor and here are my answers to my own questions + extra notes around this component.

> we can't target elements by ID within pyExec or other utilities because IDs in Shadow DOM are not reachable from the outside.

This is not only a bummer but it blocked me from implementing a full Shadow DOM based component because any time we use `target="element_id"` on the *Python* side, if such element ID is inside a *shadowRoot* there's no way `Element(id)` or even `document.querySelectorAll('#' + id)` would be able to reach that node.

This is fundamentally a blocker for any component that would like to use Shadow DOM and target elements within its shadowRoot and we need to find a solution to this issue.

As we monkey patch already `attachShadow` I do have a solution in mind but I'd like to discuss this further with the rest of the team.

> I don't understand what we are testing [here](https://github.com/pyscript/pyscript/blob/main/pyscriptjs/tests/integration/test_py_repl.py#L39-L48) because the content of a py-repl [gets removed](https://github.com/pyscript/pyscript/blob/main/pyscriptjs/src/components/pyrepl.ts#L49-L50)

I do know now what we were testing: the editor content should contain whatever initial code was inside the `<py-repl>` and I had to modify the test to address internal *shadowRoot* content which apparently is transparent to Playwright ... kudos to that but also tests can be very misleading because differently from the DOM, if we address via `.locator(CSS)` some element inside a *shadowRoot* Playwright returns it but the real-world-Web wouldn't. We need to keep this in mind.

> Last, but not least, the `<div class="py-repl-output"></div>` is a bit obscure to me

Not anymore, I was mislead by the current live example that doesn't put anything in it, while current main code shows results in there too + it shows up in the terminal if not specified otherwise.

- - -

### Still not perfect

If the outer container has very strong styling like it is in the case of reveal, it is still possible our repl would show weirdly ... but that's also on **codemirror** because it uses a lot of JS to style its nodes and as soon as it doesn't understand something in the current layout (reveal one, as example, hen the devtools is opened on the side) it messes up the cursor.

The fact it even uses a cursor as a div and it hides the native browser cursor for the content editable div was not only a surprise but the source of various issues and it shouldn't be on us to fix those issues, imho.

A part from that, the editor is now fully self-contained with a `:host { all: initial; }` attached to the *shadowRoot* to avoid being fully destroyed by external CSS but the repl itself can't be really contained as Shadow DOM because of the unreachable IDs it uses to show the outcome, as example.

That being said, everything else seems to work better and in a more secured way (less conflicts with 3rd party libraries).

- - -

### Related yet off-topic thoughts

The `<py-repl>` is yet another component that might contain *Python* code in it to bootstrap itself within its content and this suffers all the same edge cases the `<py-script>` does.

While I have been thinking that a `<script type="py-repl">` would be an awesome alternative, and a logical `<script type="py-script">` companion, this strategy doesn't really scale.

During the MR I've been thinking so many times why we don't instead define a **single component** to write python code and, if such component has a `target="py-repl"` or a specific *id* it's the only component where people can always safely write any code they like. Right now that component is `<script type="py">` which should be the only place people write code and its content might be used to bootstrap a repl without having double the amount of entities and DOM parsing issues going forward with these components that include possibly invalid HTML or text able to mess up the page or the source code itself (I've recently fixed the mathplot example that was showing `&lt;` in the source where users couldn't copy and paste that source and there are other issues around SVG we need to fix ASAP too).

**example**
```js
<script type="py" target="py-repl-id">
print("Hello World")
</script>
<py-repl id="py-repl-id"></py-repl>
```

If there's no `src` attribute but there is a `script[target="${this.id}"]` on the page, the content gets populated by that source instead of having multiple places where python can be written ... I'd say "*let's have one source of truth for code*" but I understand this would be some breaking change now but I really think we should consider moving into a direction where code goes in a single component that can be smart at not executing itself if it targets some other plugin/component and plugins/components can refer to that source even in parallel, if needed, without messing or duplicating the amount of code in the page.

**Comment by fpliger** [comment]
Thanks for this work @WebReflection ! This is great. Also, sorry for the slow response time here... just when I thought I cleared enough my schedule to finally get back to a good amount of time here, a really bad cold got me and I've been K.O. most of the week :/

Here are some comments below:

> As we monkey patch already attachShadow I do have a solution in mind but I'd like to discuss this further with the rest of the team.

Looking forward to it! It'd be also a good opportunity to align on "what the ultimate version of `<py-repl>` should do?" or, to put it in a different way "what is the problem `<py-repl>` trying to solve and what are the user facing features it ultimately should expose?"

> I do know now what we were testing: the editor content should contain whatever initial code was inside the <py-repl> and I had to modify the test to address internal shadowRoot content which apparently is transparent to Playwright ... kudos to that but also tests can be very misleading because differently from the DOM, if we address via .locator(CSS) some element inside a shadowRoot Playwright returns it but the real-world-Web wouldn't. We need to keep this in mind.

Ah, that's definitely something to keep in mind and to be captured.

That actually is a good time to mention one thing that really bothers me about our tests. They don't walk the readers through the process of what they are testing and often lack docstrings or comments. I really appreciate tests that have a structure and are explicit in their intentions... (like, commenting `GIVEN a, b, c...`, `WHEN bla bla happens`, `EXPECT this this and that`)

> If the outer container has very strong styling like it is in the case of reveal, it is still possible our repl would show weirdly ... but that's also on codemirror because it uses a lot of JS to style its nodes and as soon as it doesn't understand something in the current layout (reveal one, as example, hen the devtools is opened on the side) it messes up the cursor.

> The fact it even uses a cursor as a div and it hides the native browser cursor for the content editable div was not only a surprise but the source of various issues and it shouldn't be on us to fix those issues, imho.

Agreed. Not sure it's fixable upstream either..  I think it's a total fair point to make it work for most cases and declare "it has issues with Reval, A, B, C due to how both manage their style/implementation.

We can also encourage plugins that add a different REPL implementation based on alternatives to codemirror but I don't think it's an urgency for the core team. There's just so many things we need to do before that...

> Related yet off-topic thoughts

Oh man, this is a COW (credit to @mchilvers for the CanOfWarms name here 😝  ) but, yeah, I agree that we should sit down and try to finally come up with a more solid design for this. I've been thinking about this problem as well and I think we are more aligned than we were in the past. I'd love to chat about this early next week when I'm back and see if we can confirm the areas where we are aligned and try to understand each other on the areas where we arent to come up with something like a joint proposal

**Comment by WebReflection** [comment]
@fpliger thanks for taking the time to answer me despite your not-so-great form and I agree with you tests should have more comments, at least those using Playwright only features obscure to the Web. I will pay more attention next time and write, or add, those comments to help the future me or anyone else on the team, understanding what we're testing, how and/or why. Looking forward to chat next week and today I'll try to address / investigate / experiment a solution for IDs that are contained within Shadow DOM nodes but there are caveats to consider in there too so ... let's see if my idea works at all or it creates just more convoluted shenanigans.
