### ISSUE TITLE
The js.createObject example from the pyscript.net documentation doesn't work

### ISSUE THREAD

**Issue by owenlamont** [pyscript/pyscript#1520]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I get this error when copying the js.createObject example code from the pyscript.net documentation into pyscript.com

![image](https://github.com/pyscript/pyscript/assets/12672027/6d642ab1-6fb8-4a66-80b9-c2866b3301cf)

### Console info

```shell
logger.ts:39 [pyexec] Python exception:
Traceback (most recent call last):
  File "/lib/python3.10/_pyodide/_base.py", line 460, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/_pyodide/_base.py", line 306, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 10, in <module>
AttributeError: createObject
```

**Comment by JeffersGlass** [comment]
Did you also copy the related JavaScript code [from that documentation](https://docs.pyscript.net/2023.03.1/guides/passing-objects.html) into `index.html`?

```html
<script>
    function createObject(object, variableName){
        //Bind a variable whose name is the string variableName
        // to the object called 'object'
        let execString = variableName + " = object"
        console.log("Running '" + execString + "'");
        eval(execString)
    }
</script>
```
This is the code that actually defines `createObject` on the JavaScript side, so that it can be imported on the Python side. I suspect you're missing this, hence the attribute error on createObject the first time it's used on line 10.

**Comment by owenlamont** [comment]
🤦🏻‍♂️ No I hadn't, sorry for raising this!
