### ISSUE TITLE
[NEXT] Display and other objects are loaded dynamically from JS, polluting globals()

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#1651]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Logging this as a Bug (because I think it's a regression compared to Classic) but it could very well be better as discussion ... (details :) )

The current way add all the PyScript `stdlib` and other things (like injecting `window`, `document`, etc.. is pretty much like the initial implementation of PyScript did (executing in global) rather then based on modules. This has already been discussed and have many drawbacks that have been surfaced in previous discussions. 

It'd be beneficial to align this side of things with Classic, and load it all as modules. 

So far, here are the areas that I think are related to this issue:

* `display`: That is currently [a JS function being injected in the Python namespace.](https://github.com/pyscript/pyscript/blob/e48e6276e15b5510ced7af265a26dfee7d9c58a1/pyscript.core/src/core.js#L93-L118) I'm not sure of the reasons of the JS layer before we call display at the Python level (injected as `pyDisplay`) but I guess it's to manage `currentElement` and what's the element we should `display` to in case no `id` is explicitly specified. My guess here is that we could do the same in Python if we exposed/injected `currentElement` 
* injections in worker: right now, we are [currently injecting](https://github.com/pyscript/pyscript/blob/e48e6276e15b5510ced7af265a26dfee7d9c58a1/pyscript.core/src/core.js#L142-L153) polyscript's `window`, `document` and `sync` in the worker namespace in order to make `document`, `window` and `sync` work inside a worker. One of the drawbacks here is that we now need to diverge codebase for `main` vs `worker`. If we only injected a `__in_worker__` flag (that we could actually inject/modify at the `pyscript` package level) we can then manage that dichotomy at the python level and keep the JS side flow without having to deal with too many conditions. In this case the python side result in something like this:

pyscript
```python
if __in_worker__:
    import polyscript
    document=polyscript.xworker.window.document
    window=polyscript.xworker.window
    sync=polyscript.xworker.sync
else:
    from js import window, document
    sync = None # or something similar... we don't use/need sync in the main thread, right?
```
and then any client code could simply do:

```python
from pyscript import window, document, sync
```

So, proposal here is that we:

* put all the python related files into `src/python`
* load all Python things as modules
* intentionally only load things to `globals` when needed and preferably
* change `display` so its logic is all implemented in the same place
* if we implement the above in `python`, we inject the `currentElement` in the `pyscript` namespace so that `display` can know the `currentElement` to display to
* add/inkect  __in_worker__ to the `pyscript` module scope so that we can use to dynamically load the right objects in `main` or a `worker`

**Comment by WebReflection** [comment]
I don't understand any of your pointers ... both are a module, not globals ...

in python code you need to `from pyscript import document, window`

in python worker code you need to `from pyscript import document, window`

in no circumstance these are globals ... they use `registerJsModule` in the main and they create a `pyscript` module in the virtual file system in workers ... because I don't understand this bug I can't formulate any opinion on this matter but to me this can be closed already as no global leak happens and all primitives to avoid that are already in place ... you highlighted these, no `display` is global, neither `document` or `window`.

Why, where, or ohw did you manage to use `pyscript` stuff without importing from the `pyscript` module?

**Comment by WebReflection** [comment]
Also ...

> and then any client code could simply do:
> `from pyscript import window, document, sync`

that's exactly the case already

**Comment by WebReflection** [comment]
> [it does seem to add FS to the global scope ](https://github.com/pyscript/pyscript/blob/e48e6276e15b5510ced7af265a26dfee7d9c58a1/pyscript.core/src/core.js#L143).

you mean the module global scope, right? would `import pyodide_js` add `pyodide_js ` in the module too? if that's not the case then we can change just that. The rest does already what needs to be done for display to work but the culprit here is that workers need **strings** to work so any worker hook has to be a string because that's what passed to the Worker constructor: all code as string, there's no runtime when this code is passed and there's no way to import remotely that file.

Let's discuss this later though so maybe we better understand each other.

**Comment by WebReflection** [comment]
This MR addresses the global leaks concern within the module or within the Worker https://github.com/pyscript/pyscript/pull/1655

It's literally 6 lines of changes needed but to answer your question about why we need `registerJsModule`, it's the only way to grant a better display with an automatic target and it was suggested as approach by @hoodmane after previously leaking that instead globally.

The current MR works (tested manually locally) and it still use `display.py` as artifact as that's what it is.

It is not possible otherwise to import from pyscript as file because `display` itself is an export of `pyscript` so that `pyscript` needs to be registered as a module on main as it is, so that the ID of the target is provided by default, and it's convenient to have it saved once as file per each Worker that is bootstrapped.

Could the `display` instead use `from polyscript import window, document` ? well **no**, because polyscript doesn't have any knowledge of the `js` import / namespace as its name suggests it's for all sort of runtimes, not just Pyodide or MicroPython, so there's that too ... the `from pyscript import window, document` is a *PyScript* feature, not a *polyscript* one ... I hope this makes sense and reasons well.

**Comment by hoodmane** [comment]
Frequently people set `__all__` to indicate which names are intended to be exported from a python module as opposed to which things are imports and just incidentally there. But `import name as _name` is generally good practice.

**Comment by WebReflection** [comment]
@fpliger *actually* ... I finally see leaks in the main for `window` and `document` but I did fix leaks in the worker. I'll try to find a better solution for the main case.

**Comment by WebReflection** [comment]
FYI this MR fixed all the global leaks issues in both main and worker: https://github.com/pyscript/pyscript/pull/1655

As it landed already I am closing this one but if we really don't like the current state we can talk about it further.

Currently, what is really important to understand, is that the `registerJsModule` is needed because:
  * we both solve the `target.id` automatically to improve the `display` functionality
  * we also pass a different `PyWorker` that instruments the `XWorker` out of the box
  * we pass directly the real `window` and `document` without needing to do an indirect Proxy dance via `js`

On the Worker side, we create a `pyscript.py` module in the FS without leaking any variable because:
  * we need to be able to instrument `display` to use the `xworker.window` and `xworker.document` instead of the `js` one, as these would break otherwise
  * we can't import these directly from *polyscript* as `xworker` does not exist in the main, it's a *worker* related export only

There is an outstanding argument that using `display.py` this way, as string artifact, does not allow us to directly test that code as python file but the truth is that we should never test `display.py` in isolation because it does different things accordingly if it's in main or in a worker and the only way to properly test it is to use *PyScript* core so we definitively need better integration tests there but we definitively don't need to test that file in isolation as that's not real-world code.

We could, however, quickly mock it if any test in isolation is desired, simply adding `from js import window, document` on top of the file ... arguably we could write that already and drop that line while instrumenting it as code but that's still doable in a separate MR.
