### ISSUE TITLE
[next] <script src="..."> or <script worker="..."> should error if there is also inline content

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1714]
This is a mistake which I made yesterday:
```html
<script type="py" worker="main.py">
import main
main.do_something()
</script>
```

I had no idea why `do_something()` was not being executed. It took a while before realizing that I wrongly used `worker="main.py"` instead of just `worker`.

If I understand correctly, if you have `worker=URL` or `src=URL`, the inline content is just ignored.
I think that instead we should emit an error if the inline content is non-blank (i.e., it contains anything else than just whitespace)

**Comment by WebReflection** [comment]
I respectfully disagree ... having a `src` or a `worker` url works the same as before but one can write **any comment** in that element and that is just fine and helps self-documenting what's going on:

```html
<script type="py" worker="main.py">
  the main.py file does something cool
  and this comment has no issues whatsoever
</script>
```

This helps documenting examples or anything else and there is a documentation to read about attributes where both `src` and `worker` have priority and it's well written.

We can't fix what's currently handy because people will do any sort of mistakes and that's why we have docs.

**Comment by WebReflection** [comment]
btw, this is **definitively not a blocker** as it's about reading the docs, not a defect to me, or even a bug ... everything is expected here.

**Comment by JeffersGlass** [comment]
To me, `src` and `worker` are different cases, because `<pyscript src>` (with no value) causes an error, while `<pyscript worker`> is defined and useful. Additionally, the `src` attribute is a thing on the web already, whereas `worker` is unique to PolyScript.

For the `src` attribute, I think we should retain consistency with web practice, and not error when there is both a `src` and inline code. Let's say I am -0.5 to error in this case.

We might want to take a stronger hand with the `worker` attribute - and since it's PolyScript's invented attribute and unlike any existing web/script attributes, I think we have more latitude. Your use case, I imagine, was moving from inline worker code (`<pyscript worker>`) to worker code in a separate file (`<pyscript worker="main.py">`) or vice versa, which is something one wouldn't do with with the `src` attribute. I'm +1 on erroring when both `worker="..."` and inline code are present.

**Comment by WebReflection** [comment]
> If you have something which is unexpected and confusing

unexpected accordingly to whom? it's highly subjective and there's no *standard* behavior, as Jeff mentioned, to expect anything at all ... I've shown a case where having content is useful for examples and learning purpose, but then again 

> Personally, I think that allowing code which is silently ignored is Very Bad ™️, and the disadvantages are much superior than the advantages.

that's how `<script src="file">/* any content */</script>` works **by standard definition** ... there is no error in there so you are asking to have a non consistent behavior for the sake of your own subjective feelings ... I am afraid I don't agree, standards don't agree, consistency doesn't agree neither ... so I am -1 to this.

```html
<!doctype html>
<html lang="en">
  <head>
    <script src="./file.js">
      This is allowed by Web standards.
      This is allowed by <py-script src> too.
    </script>
  </head>
</html>
```

**Comment by WebReflection** [comment]
to clarify, if `worker` has to fail, so should `src` ... if `src` doesn't fail, so shouldn't `worker` ... these are equivalent from an API point of view, their behavior should be equivalent too. They mean either *source* or *worker source* and I think we should close this issue, or I think we should list exactly why we ike to introduce inconsistencies and we want to ignore what Web standards allow purposely. `<script src>` doesn't throw and doesn't evaluate, it's a user mistake and users mistakes in the programming world are part of the learning process.

**Comment by WebReflection** [comment]
**what if** we show a `console.warn` instead so that:

  * it's not obtrusive
  * it still allows comments in nodes or content for the 3 variant debugging case (no worker, just worker, worker that points to a file with the same content)
  * it shows to slightly more advanced users what's going on, so that Antonio case is partially covered
  * it shows the same warning to `src` with content so it's kept consistent

I would be +1 to this approach as it's both helpful and it can be a consistent error to show (maybe we need to add a `PYXXXX` error for these cases?) ... thoughts? I think as compromise it should work.

**Comment by JeffersGlass** [comment]
I’m +1 to this suggestion @WebReflection - keeps it consistent with at least the *behavior* of the browser’s `src` (remote file takes precedence inline content) while still providing at least some guidance to new/novice users.

**Comment by WebReflection** [comment]
heck I think this should be a **users-hints** plugin where:

  * it can be disabled in production via `!users-hints`
  * it can help new/novice users better understanding more than just this use case in the future
  * it won't pollute the core with stuff you encounter once in your life and then you get it and move on (so you disable it)

this would be very clean and I am sure desired, specially because users not new nor novice will avoid that code to ever run in their projects (enabling it with ease if needed).

**Comment by antocuni** [comment]
> to clarify, if `worker` has to fail, so should `src` ... if `src` doesn't fail, so shouldn't `worker` ... these are equivalent from an API point of view, their behavior should be equivalent too. 

+1 on this. Whatever decision we take, they should have the same behavior.

> it's a user mistake and users mistakes in the programming world are part of the learning process. 
[cut]
> there is documentation that is very explicit

this is precisely my point. I didn't (fully) read the docs and/or I misunderstood them. I made a mistake in using pyscript. My bad.

I think that the best service that we can do to our users in cases like this is to try to detect as many mistakes as possible and warn/inform/guide them to correct them. Silently ignoring things is never a good idea, IMHO.

I am perfectly aware that the standard for JS is different. I think that JS made a mistake. I would like pyscript to be easier/better than JS. As it happens often, there is a trade-off between:
1. adherence to existing JS practice and behavior
2. "fix" an existing behavior which doesn't serve well the users (IMHO, of course)

To be very explicit, I think that the following are not good strategies to fix these kind of problems:
- say "RTFM". Yes, in an ideal world, people would read the full docs before using a product. But this is almost never the case, and it's certainly not the case for a vast part of the "99%" that we are targeting
- write messages, warning and errors to the JS console. I don't expect our users to look at devtools, to know that they exists and even that they possibly *can* look at them (e.g. on mobile).

**Comment by WebReflection** [comment]
the thing is also a documentation issue ... if anyone searches for `<script src>` they gonna be informed that if it's there, it has precedence over the content of the script. This it the Web standard definition and you're a bit late to disagree to a 20+ years consolidated standard.

Showing anything on users' face for something perfectly acceptable and documented is not my cup of tea, specially if I want, for documentation or training purpose, put comments inside my scripts to explain what the `src` does or what the `attributes` do, or why I've used those in the source code of the page.

This is good for everyone, while showing warnings is not ... so I think we should vote here because me and Jeff are OK with my last resolution and at least this should be configurable as I would never want that, neither errors on pages, so that the plugin solution seems more than reasonable to me, whatever we end up being obtrusive in terms of warnings on the page, or relaxed with a console error, something we ask for issues filed too, something any Web developer learns at day 0, imho.

They are leaning PyScript? Good, they're learning Web development, I'd like to sse data around how many users learning Web developers don't know devtools exist too.

**Comment by ntoll** [comment]
Yeah... so RTFM, the existence of dev tools and understanding how to read an error message and related stack trace are NOT answers to problems folks encounter while coding.

Rather, they are things folks learn to understand after experience, and they may encounter them as part of trying to fix their own problems.

> STUDENT: O Guru, what is the secret of success?
> GURU: Good judgement.
> STUDENT: How do you get good judgement?
> GURU: Experience.
> STUDENT: How do you get experience?
> GURU: Bad judgement!

We all do this on our journey to experience. :-)

I'm glad I have colleagues who appreciate this. :rocket:

**Comment by WebReflection** [comment]
@ntoll I don't understand what is your point but also nobody said just RTFM ... we're informing users something happened which would've fixed Antonio confusion ... we're happy (me and Jeff) to do it via `consolw.warn`, I'd be compromising only if these *warnings* (as these are not errors per se as there's nothing wrong in having content in a script (specially comments) will be offered as plugin or as part of the error plugin ... as anyone above the day 0 would not want those in production, specially pages showing examples with comments to explain what's going on.

**Comment by ntoll** [comment]
I was vibing on @antocuni's point:

> To be very explicit, I think that the following are not good strategies to fix these kind of problems:
>
> * say "RTFM". Yes, in an ideal world, people would read the full docs before using a product. But this is almost never the case, and it's certainly not the case for a vast part of the "99%" that we are targeting

It's not a criticism in any way, rather an acknowledgement of violent agreement. :boom: :+1:

**Comment by WebReflection** [comment]
Sure, we can stop writing docs too ... but please let's move this conversation forward and clarify I've never said RTFM but if users look for documentation they'll learn we should not throw an error + there is nothing wrong in having comments in scripts so I don't understand at all what we're trying to solve there ... no confusion, better on IDEs, better on sources, helping users too for examples ... I also follow Web standards in general and I thought we were aligned there.

https://html.spec.whatwg.org/multipage/scripting.html#attr-script-src

**Comment by WebReflection** [comment]
Maybe I can move the issue forward: do we agree comments are fine but content is not?

  * **yes** we can throw if content is not a comment
  * **no** we throw always as part of the `error` plugin (unless we want a `warning` or `guidance` plugin too for these things that are not about errors in code)

**Comment by WebReflection** [comment]
>  but I'm not willing to fight for this :))

it's rather about *highlights* and IDE default support for that ... you made this argument before in other venues, you should understand that if I want to **help** a user with an example and a comment in it, it's better if it doesn't look a broken suggestion out of the box ... look at this example one more time ;-)

```html
<script type="py" worker="main.py">/*
  the main.py file does something cool
  and this comment has no issues whatsoever
*/</script>
```

### Conclusion

  * we are going to throw an error via error plugin or `console.error` when plugin is explicitly disabled
  * we are going to ignore either Python or JS (naaah, C, C++, others :P) content only to help us help users with examples and comments whenever that's needed

If I get at least 2 +1 here I'll move forward with the patch pre-RC, thank you!

**Comment by WebReflection** [comment]
beside the thumbs up I'd like to see, may I ask how many ways Python comments are written?

```python
# single line

"""
multi
line
"""
```

is there any other hackery around comments I am not aware of? thanks for eventually letting me learn something new :heart:

**Comment by JeffersGlass** [comment]
> we are going to throw an error via error plugin or console.error when plugin is explicitly disabled
we are going to ignore either Python or JS (naaah, C, C++, others :P) comments only to help us help users with examples and comments whenever that's needed

I can +1 this as well - I can see the logic in it. 

(I was going to make a joke here about using `eval()` to identify Python comments, but I didn't want anyone to think I was actually serious.)

**Comment by WebReflection** [comment]
thanks, I've still learned something and indeed if I use my IDE to comment out multi line Python it uses the `#` or the `//` approach ... I'm OK with the resolution and I am working to fix this ASAP.

**Comment by ntoll** [comment]
I double dare you @JeffersGlass :rofl:

**Comment by WebReflection** [comment]
> about using eval() to identify Python comments

we should definitively `eval(...)` JS too as nothing could possibly go wrong there :+1:

**Comment by WebReflection** [comment]
for the worker story we need to move forward (after release) this issue https://github.com/pyscript/pyscript/issues/1678

but the MR that throws on ambiguous intents is here: https://github.com/pyscript/pyscript/pull/1724

**Comment by WebReflection** [comment]
MR landed.
