### ISSUE TITLE
[next] improve py-config tests

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1729]
**NOTE**: this is not a blocker for the upcoming RC1 release, we should tackle this after it.

The following two tests in `test_py_config` are very weird:
https://github.com/pyscript/pyscript/blob/77b40aa34817b0cb209ccf9d138d39eed8297136/pyscript.core/tests/integration/test_py_config.py#L53-L104

They use `document.currentscript._pyodide` which is undocumented and works only in the main thread.
Plus, if I understand correctly @WebReflection says that this `_pyodide` attribute should not be there and it's not clear where it comes from.

The original discussion is here (this and following comments):
https://github.com/pyscript/pyscript/pull/1723#issuecomment-1723736975

The proposed solution is to design way to officially expose the config to the python world, so that we can rewrite those tests in a more direct way.

**Comment by WebReflection** [comment]
To be honest, I think for consistency sake all `<script type="py">` and `<py-script>` tags register themselves as `currentScript` (it's explicit within the code) so what bothers me is that only `<py-script>` custom elements get `_pyodide` [attached](https://github.com/pyscript/pyscript/blob/next/pyscript.core/src/core.js#L240-L246).

Regardless, if all we want is to know the parsed and passed config value, somehow testing that our TOML library just works so it's weird as a test in the first place as we should test config expected side-effects, or config errors propagated, not the config itself as that doesn't belong to our code (in term of parsing), I think it'd be much better to actually export that via the module itself and purposely *leak* it as global `py_config` or `pyConfig` so that we can read it via `js.py_config` and test whatever we think we should test there.

**Comment by ntoll** [comment]
I agree we need a way for folks to programmatically get to the configuration object. They may be plugin authors, or perhaps the config contains app specific details that some Python requires. In any case, I hope we can do it in an obvious way like this:

```python
from pyscript import config
```

To get a dictionary of the config. Similarly, having a `currentScript.config` object in the JavaScript world feels like the right place to me (or somewhere similar).

I don't like that we have `_pyodide` attached to anything like a `<py-script>` tag. That's just weird. 🙂

**Comment by WebReflection** [comment]
In my opinion, the `config` or `configs` export will be something like this:

```js
[
  {type: "py", config: { ... }, ...anythingElse},
  {type: "mpy", config: { ... }, ...anythingElse},
]
```

or an object literal like this:

```js
{
  "py": config,
  "mpy": mconfig
}
```

I like both ways, and it's pretty easy to offer too.

**Comment by antocuni** [comment]
I prefer the object literal way. It makes it easier to use from JS, e.g.:
```js
console.log(config.py.packages);
```
if it's a list, you would need to iterate over the list to find the "correct" entry

**Comment by WebReflection** [comment]
fully addressed in here https://github.com/pyscript/pyscript/pull/1743
