### ISSUE TITLE
Is pyscript safe?

### ISSUE THREAD

**Issue by Fundi1330** [pyscript/pyscript#1825]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I want to build a learning platform for Python. And I want to do coding questions. While pyscript is working on front-end side and not communicating with the back-end it should be safe. But is it really safe? What are the vulnerabilities?

**Comment by WebReflection** [comment]
PyScript is as safe as JS is on the browser so unless you have some particular concern in mind (but again, it's just an interpreter running in a browser) I am not sure why this is an issue instead of a discussion or a Discord question.

Closing, but feel free to ask more or present a use case you think is not safe or problematic, thank you.
