### ISSUE TITLE
DataFrame rendering on console displays First  and last columns.

### ISSUE THREAD

**Issue by nasrin1748** [pyscript/pyscript#1916]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Should have displayed all columns instead of first and last.
https://_12.pyscriptapps.com/pandas-copy-36373/latest/
<img width="555" alt="21" src="https://github.com/pyscript/pyscript/assets/79505893/6113d7c6-0b75-4506-832d-86a68114f1ce">

### What browsers are you seeing the problem on? (if applicable)

Microsoft Edge

**Comment by WebReflection** [comment]
I think Xterm tries to not overflow the available console area so you see those `...` in there. I am not sure there is an option to tell Xterm to not shrink tables but we wither have a *fit best* layout there, or a *stretch everything* ... and not both.

Maybe we should think about a special attribute for the terminal *layout* so that users can fine-tune as they need?

**Comment by nasrin1748** [comment]
Sounds great. Let's try our luck.

**Comment by gitozi** [comment]
Isn't that compact format standard behavior of pandas? 

At least for my normal shell (bash, Linux) it shows all columns (only) if I set the respective pandas options, i.e. 

`pandas.set_option('display.max_columns', None)` 

and if you do prefer wraparound of rows over wraparound of the table then also sth. like 

`pd.set_option('display.width', 1000)`. 

See also e.g. https://stackoverflow.com/questions/49188960/how-to-show-all-columns-names-on-a-large-pandas-dataframe.

**Comment by nasrin1748** [comment]
Yes this shows all the rows.Its the standard behavior of pandas.I am trying to get all columns in single line by adding horizontal scrollbar.If you have any solution related to that it will be helpful.Adding scrollbar to terminal?

**Comment by WebReflection** [comment]
I did (sorry for the delay) investigate a bit this issue and there is a suggestion in XTerm project itself: https://github.com/xtermjs/xterm.js/issues/2544#issuecomment-550467386

Basically, a terminal must be confined in width to have an understanding of where the cursor should go next ... so it's normal that if the content to show cannot wrap around the terminal boundaries it "*leaks*" in new lines, the same as your Desktop console/terminal ... if you write something too long without spaces it wraps to the next line (just resize your window after a long print) so that programs usually try to fit best in the terminal boundaries.

Accordingly, I think the solution is indeed to wrap the terminal into a target (via target attribute) that has no width limits or it's big enough to contain all the details you are after, so that such target can be placed into a container with an horizontal scroll with ease.

That also boils down to the fact we don't have a solution and, probably, we also shouldn't have a solution to this, as it would slow down or interfere with native/natural terminal emulation which is usually not desirable (plus we use an autofit plugin for all other cases which are way more common).

I hope this reply reasons well to you, I am afraid I am going to close this as I don't see any possible follow-up action for us to take around this matter.
