### ISSUE TITLE
PyScript.com fails to highlight extensions .mjs & .cjs

### ISSUE THREAD

**Issue by GoToLoop** [pyscript/pyscript#1927]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Extension type .mjs is very important to emphasize a JS file is to be loaded as a module.

While .cjs is important for NodeJS to tell apart a ES6 module from a CommonJS 1.

As an example, files "ball.mjs" & "global.mjs" are treated as plain text instead of JS:
https://PyScript.com/@gotoloop/bouncing-colorful-balls

Could you please enhance PyScript.com to syntax-highlight those JS extensions?

**Comment by WebReflection** [comment]
> Extension type .mjs is very important to emphasize a JS file is to be loaded as a module.

On the Web, extensions are meaningless and PyScript supports only ESM as so does the web. Any import `.js` works without issues and some outdated server might never understand `.mjs` extension, so that if the mime-type is not `text/javascript` or `application/javascript` that file cannot be imported by browsers, no matter the extension name.

In NodeJS there are many ways to enforce modules as ESM, adding `"type": "module"` would already handle all `.js` files as ESM. The *CJS* has no meaning on the Web and if you use your own version of `require` that will work as those files will be evaluated as plain text, which is desired, while as modules these should fail, as the two module systems are not interchangeable.

All that being said, I believe the service should support `.mjs` seamlessly as that's currently a standard mime-type for modern server so it should be understood as such. **However**, this project is about the PyScript library itself, the Web / service exists as different project so I am pinging @FabioRosado here as he would know best what needs to be done and where (which is *not* in this repository).

Thanks for your patience and for filing the issue, I hope the `.mjs` part at least can be resolved soon.

**Comment by FabioRosado** [comment]
Hello and thank you @WebReflection for pinging me, this should be a one line fix, will implement today and then we will have to deploy 😄

**Comment by GoToLoop** [comment]
Add both ".mjs" & ".cjs" as well.

Maybe also TypeScript extensions such as ".jsx", ".tsx", ".ts", ".mts", ".cts".

**Comment by WebReflection** [comment]
> Add both ".mjs" & ".cjs" as well.
> 
> Maybe also TypeScript extensions such as ".jsx", ".tsx", ".ts", ".mts", ".cts".

one thing is to fix standards, one thing is to enable all possible variants that *are not standard*. I don't think you ever need those extensions to behave differently from `plain/text` but until those extensions are not part of standards, it's counter-productive to enable these in any way as we're just moving the issue we have here to the next live service where none of those extensions would return a meaningful mime-type neither.

`.mjs` has a standard mime-type defined by all standard bodies, everything else is not there yet and nobody should push for it, imho.

**Comment by WebReflection** [comment]
Closing as there's nothing to do for us in this specific repository.
