### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Rinshin-Jalal** [pyscript/pyscript#196]
As a Pythonista😀. 

I want to use print as something console.log✔️

instead of printing into the screen😐

**Comment by Shahin-rmz** [comment]
> As a Pythonista😀. 
> 
> I want to use print as something console.log✔️
> 
> instead of printing into the screen😐


What does console.log do?

**Comment by JeffersGlass** [comment]
One simple way to log to the console is as follows:

```
from js import console
console.log("Hello, world from Python!")
```

If you wanted all printed output to go to the console, you could replicate [the behavior of the Output Manager class](https://github.com/pyscript/pyscript/blob/442af7bd97095e67df9dd2173e5997cb467a5d2b/pyscriptjs/src/interpreter.ts#L388-L393) and point sys.stdout to a function which writes to the console. This is a quick-and-dirty version:

```
from js import console

class consolePrinter:
  def write(self, *args):
        for a in args:
          console.log(a)

sys.stdout = consolePrinter()

print("Hello world in the console, via a print statement")
```

**Comment by mouhandalkadri** [comment]
or you simply could do something like this
```
from js import console
print = console.log
print("Hello World !!")
```

**Comment by JeffersGlass** [comment]
@mouhandalkadri That's true, and certainly simpler. It does lose a little of functionality of print's keyword arguments, so it's not quite a drop-in replacement.

`from js import console
print = console.log
print("Hello", "World", sep = "-", end = "!")`

Yields:
![image](https://user-images.githubusercontent.com/1931111/166849750-52f0ef9c-8e29-4054-aad0-54c0695fb4de.png)

But that's just me quibbling, because my [longer example earlier](https://github.com/pyscript/pyscript/issues/196#issuecomment-1117821460) also gives wacky results due to [the way print() interacts with stdout](https://github.com/pyscript/pyscript/issues/103#issuecomment-1115168418):

`from js import console

class consolePrinter:
  def write(self, *args):
        for a in args:
          console.log(a)

sys.stdout = consolePrinter()

print("Hello", "World", sep = "-", end = "!")`

Yields
![image](https://user-images.githubusercontent.com/1931111/166850002-a4d93e7d-20f4-4ee0-9344-601b90de2065.png)

So, @Rinshin-Jalal , take your pick of methods.

**Comment by Rinshin-Jalal** [comment]
> @mouhandalkadri That's true, and certainly simpler. It does lose a little of functionality of print's keyword arguments, so it's not quite a drop-in replacement.
> 
> ```
> from js import console
> print = console.log
> print("Hello", "World", sep = "-", end = "!")
> ```
> 
> Yields: ![image](https://user-images.githubusercontent.com/1931111/166849750-52f0ef9c-8e29-4054-aad0-54c0695fb4de.png)
> 
> But that's just me quibbling because my [longer example earlier](https://github.com/pyscript/pyscript/issues/196#issuecomment-1117821460) also gives wacky results due to [the way print() interacts with stdout](https://github.com/pyscript/pyscript/issues/103#issuecomment-1115168418):
> 
> ```
> from js import console
> 
> class consolePrinter:
>   def write(self, *args):
>         for a in args:
>           console.log(a)
> 
> sys.stdout = consolePrinter()
> 
> print("Hello", "World", sep = "-", end = "!")
> ```
> 
> Yields ![image](https://user-images.githubusercontent.com/1931111/166850002-a4d93e7d-20f4-4ee0-9344-601b90de2065.png)
> 
> So, @Rinshin-Jalal, take your pick of methods.

That works 
but I said it would be better if it is available directly in this library itself

majority of programmers uses `print()` and `console.log()` for debugging

It would be very useful if print console.log it `naturally!!` without these methods

**Comment by mouhandalkadri** [comment]
@JeffersGlass yes that's right
either ways, you will lose some "print" functionality.
here's a suggestion, can we write a custom implementation using console.log, preserves the whole functionality of the "print" ?

**Comment by fpliger** [comment]
Yes, can totally understand the suggestion. That's one of the areas we'll be improving soon. Right not, console "is" the default std_output but there's not a good way to better express a mix of output to DOM elements + console (+ it's likely that some parts have significant bugs). 

In addition, we will also be adding better UI widgets to support that part of the workflow as well.

Thanks!

**Comment by Rinshin-Jalal** [comment]
Ok 👌

**Comment by Rinshin-Jalal** [comment]
Ok 👌
