### ISSUE TITLE
Unable to use a PyWorker Offline

### ISSUE THREAD

**Issue by dmmiller** [pyscript/pyscript#2117]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I was trying to use a PyWorker offline, but was unable to specify that it should load pyodide.mjs from anywhere other than the default it used.

I have an app that uses a python script on the main thread.  As part of that, it creates a PyWorker.  I would like that pyworker to load pyodide.mjs (and associated files) from my server rather than `https://cdn.jsdelivr.net/pyodide/v${e}/full/pyodide.mjs`

I followed the instructions at https://docs.pyscript.net/2024.7.1/user-guide/offline/ to get my main worker loading via my own installed instance of pyodide.  Getting this to work for the worker did not work though.  It continued to load from the above link.

I tried to specify it in the config, specifying the interpreter, but this also didn't work.

Here is how I specify my config for the worker :
```
    worker_options = ffi.to_js({
        "type" : "pyodide",
        "config": {
            "files" : {
                "./python/decorators/makefilter.py" : "decorators/makefilter.py",
                "./python/decorators/maketransform.py" : "decorators/maketransform.py",
           },
        }
    })

    worker = PyWorker('python/worker.py', worker_options)
```

Happy to share more of my setup if useful.  Thanks for any help.

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome, Safari, Microsoft Edge

**Comment by WebReflection** [comment]
As explained in the [polyscript documentation](https://pyscript.github.io/polyscript/#xworker-options):

![Screenshot from 2024-07-10 10-02-49](https://github.com/pyscript/pyscript/assets/85749/bb930d45-7e2d-4d56-b821-f8fcb2e3f90f)

I've double checked the `PyWorker` and it literally just forwards details to `XWorker` so because this definitively *can* use *pyodide* offline, I believe the issue you are having is that you are not passing a fully qualified URL which is necessary to hint core that you have a full offline version of Pyodide at that address.

```python
from pyscript import window

version = window.URL.new("pyodide.mjs", window.location.href).href

PyWorker("file.py", type="pyodide", version=version)
```

I believe this should solve your issue because in that way you can provide a fully qualified URL and the rest should work out of the box as it does already in our docs example.

Please confirm that is the case, thank you!

**Comment by dmmiller** [comment]
@WebReflection , I can confirm this works.  

I was able to specify the fully qualified URL in the version field and it worked.

```
    worker_options = ffi.to_js({
        "type" : "pyodide",
        "version" : f"{window.origin}/pyodide/pyodide.mjs",
        "config": {
....
```

It was the magic of the `version` and fully qualified that made it happen.  It might be nice to update the offline docs to indicate this for workers.

**Comment by WebReflection** [comment]
@dmmiller thanks for the report ... and we should definitively improve our docs around this, although I am thinking that a version ending as `.js` or `.mjs` might be a better hint, and we could orchestrate the rest ourselves ... the thing is, workers are *Blobs* and need fully qualified URLs to work properly with foreign resources / assets, so let's see how much magic we can bring in *next*
