### ISSUE TITLE
[2024.10.2] Terminal rendering issue with long text when using input()

### ISSUE THREAD

**Issue by JoshuaLowe1002** [pyscript/pyscript#2246]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When using a long string together with input(), if the text overflows because there is not enough space, the line shows in the terminal twice. 

PyScript.com project to reproduce: https://pyscript.com/@joshualowe1002/sparkling-scene/latest?files=main.py

<img width="1433" alt="image" src="https://github.com/user-attachments/assets/d9ceaa66-0c6e-44fa-8f2c-981230ef629a">

**Comment by WebReflection** [comment]
If you change `py` with `mpy` you won't see any issue, suggesting this is a `readline` issue because:

  1. *py* and *mpy* both use Xterm.js as terminal, but in *mpy* everything looks, and works, fine
  2. *py*, differently from *mpy*, uses readline ... maybe this is the time we say goodbye to that project and port over *Pyodide* whatever logic we used in *MicroPython*?

I can't estimate the effort right now as the repl, or input logic, is pretty different (ad-hoc in MicroPython, starting from its core abilities, delegated to readline in Pyodide)

@ntoll any thought around it? I think I might personally be happy to ditch readline dependency as a whole at this point, as recently it's causing more issues than it solves (but it's been very keen and nice to solve at least *some* issue we filed in there).

**Comment by fpliger** [comment]
> ...
> 
> I think I might personally be happy to ditch readline dependency as a whole at this point, as recently it's causing more issues than it solves (but it's been very keen and nice to solve at least _some_ issue we filed in there).

Feels like it'd be good to do some discovery to better estimate the effort to address this in a way that we can prioritize compared to other things that are lined up...

**Comment by nasrin1748** [comment]
pyodide terminal adds a horizontal scroll bar for long text. Is it possible to add a horizontal scroll bar to the terminal instead of extending to next line?

**Comment by WebReflection** [comment]
@nasrin1748 let's not add requests within an issue that's unrelated ... we need to fix it in a way that works like a terminal (no horizontal scrolls on a terminal, since its first appearance) ... requests should find their place in discussion with proper reasons, use cases, and whatnot, thanks.
