### ISSUE TITLE
Plotly support

### ISSUE THREAD

**Issue by nicolaskruchten** [pyscript/pyscript#226]
Hey folks,

Great job with pyscript! Is Plotly currently supported/what would need to happen to get it supported?

**Comment by philippjfr** [comment]
Actually it's pretty simple to simply render the plot. The Panel approach will let you update the plot and interact with it though:

```html
<html>
  <head>
    <title>Plotly</title>
    <meta charset="utf-8">

    <link rel="stylesheet" href="../build/pyscript.css" />

    <script defer src="../build/pyscript.js"></script>
    <script defer src="https://cdn.plot.ly/plotly-2.10.1.min.js"></script>
    <py-env>
      - plotly
      - pandas
    </py-env>
    </head>
    <body>
      <div id="plotly"></div>
      <py-script output="plotly">
import panel as pn
import plotly.express as px

from js import Plotly, JSON
	
df = px.data.tips()
fig = px.histogram(df, x="total_bill", y="tip", color="sex", marginal="rug",
                   hover_data=df.columns)

Plotly.react('plotly', JSON.parse(fig.to_json()))
      </py-script>
    </body>
</html>
```

**Comment by nicolaskruchten** [comment]
Awesome, thank you :)

So conceivably, we could add a dedicated renderer to `plotly.io` that would auto-detect that it's in pyscript such that `fig.show()` would "just work"? Possibly something like `fig.show("divid")` I guess, unless there's some way of making that an inferrable default.

**Comment by ckavidas** [comment]
Is the question only about getting plotly graphs on a py-script HTML page? Because plotly figures have a method `.to_html()` which you could then just load into a div on the page no?

Then instead of using the `fig.show()` method you would just use your own function IE: `fig_to_div(fig, div)` which takes a figure, converts to HTML and loads it into a div.

**Comment by marimeireles** [comment]
@philippjfr's example doesn't work for me... Because I can't find `Plotly`, and if I just use the normal lib then it doesn't have the `react` attr.
When I try a simple example from their docs:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <title>PyScript Hello World</title>

    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="stylesheet" href="../build/pyscript.css" />

    <script defer src="../build/pyscript.js"></script>
    <py-env>
      - plotly
      - pandas
    </py-env>
  </head>
    <body>
      <div id="plotly"></div>
      <py-script output="plotly">
import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
#fig.write_html('first_figure.html', auto_open=True)

display(fig)
      </py-script>
    </body>
</html>

```
Also doesn't work, it says `n _call_with_frames_removed File "/lib/python3.10/site-packages/plotly/io/_renderers.py", line 533, in except webbrowser.Error: AttributeError: module 'webbrowser' has no attribute 'Error'`.

I probably just don't know about plotting enough 😅
I wonder if it's some interaction with pyodide files? That are called `webbrowser`? Not sure!

**Comment by JeffersGlass** [comment]
Interesting - both of @philippjfr's examples work for me in unstable (as of commit 00ab9a8), if `../build/pyscript.js` is changed to `../pyscriptjs/build/pyscript.js`

![image](https://user-images.githubusercontent.com/1931111/193059123-5e29d3eb-7ae6-4667-b57f-2887603e5a97.png)

Are you testing your example against the branch from PR #749?

**Comment by marimeireles** [comment]
Okay. Weird!
No. It's just my environment. There's something here interacting it badly.
Alright, so I guess... I'll close this one? Since it's working for everyone :)
Thanks for testing @JeffersGlass!

**Comment by PrParadox** [comment]
I tried @philippjfr 's example but it does not work. I think bunch of stuff has been deprecated here at the same time. I am getting await error, because it cannot be called outside of an async function. I tried to fix this by wrapping it inside an async function, and call async.run on that function, didn't work, because we are not in event loop. Moreover, pn.io.pyodide.show is also deprecated, I tried using pn.io.pyodide.write, didn't work. Can you please let me know if there is any working example for plotly in pyscript?
