### ISSUE TITLE
it is possible to manipulate the css style with pyscript?

### ISSUE THREAD

**Issue by id3at** [pyscript/pyscript#250]
it is possible to manipulate the css style with pyscript. :)

**Comment by JeffersGlass** [comment]
It is! Here's an simple method ([JSFiddle](https://jsfiddle.net/ef09nymu/2/)):

```
<py-script>
target = document.getElementById("target")
target.style.backgroundColor = "green"
</ py-script>
<div id="target">
This text will get a green background when PyScript runs.
</div>
```

Here's a longer example running in [example running in JSFiddle](https://jsfiddle.net/buet9yk7/1/) that demonstrates using both CSS properties and TailwindCSS classes (included in pyscript.css by default) to modify the css on the page.

![image](https://user-images.githubusercontent.com/1931111/167144852-419ea69e-000b-4af5-960a-9a58a1f8d90b.png)

A thing I learned while looking at this - certain css properties like `background-class` are [referred to in JS using camelCase](https://stackoverflow.com/questions/41602583/whats-the-difference-background-color-and-backgroundcolor) (e.g. `backgroundClass`), since JS doesn't allow hyphens in property names. Makes a certain amount of sense.

**Comment by antocuni** [comment]
closing as the question was answered. Thanks @JeffersGlass for the answer!
