### ISSUE TITLE
[BUG] sys.stdout.isatty raises AttributeError

### ISSUE THREAD

**Issue by ptmcg** [pyscript/pyscript#280]
**Describe the bug**
When calling sys.stdout.isatty() within a PyScript block, we get the following message (running in Chrome):

```
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 2, in AttributeError: 'OutputCtxManager' object has no attribute 'isatty' )
```

**To Reproduce**

```
<html>
    <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <py-env>
        - littletable
        - rich
    </py-env>
    </head>
    <body>
        <py-script>
import sys
if sys.stdout.isatty():
    print("sys.stdout.isatty() returns True")
else:
    print("sys.stdout.isatty() returns False")
        </py-script>
    </body>
</html>
```

**Expected behavior**
Should not get AttributeError.

**Additional context**
None

**Comment by antocuni** [comment]
Good catch. This happens because `sys.stdout` is actually an `OutputCtxManager`:
https://github.com/pyscript/pyscript/blob/bc4581d9e50286f0463285f13c015e487831fa0e/pyscriptjs/src/pyscript.py#L370-L393

It lacks many attributes/methods which are normally present on `sys.stdout`, e.g. `.fileno()`, `.flush()`, `.encoding`, etc.
As a temporary workaround, you can moneky-patch the class by yourself :):
```
python
sys.stdout.__class__.isatty = lambda self: False
```

For a proper solution, I don't know. The easiest way is to add the missing methods/attributes to `OutputCtxManager`, but I suspect it's just a matter of time before someone finds that it behaves slightly differently than CPython's stdout.
A different approach is to capture the output at the file descriptor level, similarly to what pytest does: this has also the advantage (or disadvantage?) that intercepts all the C-level `printf()`.
/cc @fpliger

**Comment by philippjfr** [comment]
I do think that `OutputCtxManager` should at least make an attempt at implementing a file-like API, even if most of the implementation details are in fact no-ops.

**Comment by fpliger** [comment]
Think this is part of the major redesign happening in #622 . The current implementation has several limitations.

**Comment by marimeireles** [comment]
Closing as fixed!
