### ISSUE TITLE
[FEATURE] PySide/PyQt support?

### ISSUE THREAD

**Issue by Sclafus** [pyscript/pyscript#305]
Will this ever support any version of PySide/PyQt, or anything based on Qt?

**Additional context**
This could make the porting of existing Python+Qt applications to a PWA trivial.

**Comment by verhulstm** [comment]
hi, thanks for reaching out :)

yes, you can use pyscript in PySide.QtWebKit

**Comment by verhulstm** [comment]
and you can use pyscript in https://beeware.org/project/projects/libraries/toga/

**Comment by Sclafus** [comment]
Hello, 
maybe I did not explain the issue well enough. I'm not talking about including PyScript in a QtWebEngine instance, but including a Qt application inside of PyScript, essentially running a Qt application in the host browser.

**Comment by marimeireles** [comment]
We used to be able to run Qt inside Pyside as far as I remember... So I think that'd be possible as long as we can access Qt inside the browser . For now we only have support for Pypi packages, correct?

**Comment by marimeireles** [comment]
Correction: it seems like we only offer support for packages in `micropip` because it's the software supported by `pyodide`, so not for now, but maybe we can think on a hacky solution. I want to bring this up in the `pyscript` meeting and ask what are @fpliger's ideas on it.

**Comment by cmaureir** [comment]
Hey @Sclafus :wave: PySide maintainer here.

During PyConUS I went to one of the PyScript open spaces where I mentioned to Fabio and the other Anaconda folks that we wanted to look into the possibility to bring Qt as a Widget Library for PyScript, because we were doing some research locally since Christian Heimes started to talk about the work on CPython and WebAssembly.

On one of the last slides from Peter's keynote, I remember "Widget Library" as one of the Future Steps, and you can see that Toga already has some examples! which is natural because now Keith joined Anaconda, so we are looking forward to have a more mature and better supported Toga :) Also @jasongrout showed interest on the Jupyter side of things! not sure if maybe there is some plan to bring https://github.com/jupyter-widgets/ipywidgets there as well. 

PySide is a different beast, because it's not written purely in Python due to the Qt/C++ dependency, that's why it's more complicated to make it work, but! in the next release 6.4.0, Qt will provide WebAssembly compatibility again (5.15 was the previous supported version) as a Technical Preview, so we are looking into how to better interact with WebAssembly. PyScript is an option, for sure, but we could even rely directly on Pyodide, and use a different approach like https://github.com/emscripten-forge/recipes (suggested by @jtpio)

Once we have something more concrete we will try to better integrate PySide with PyScript, but so far it's still WIP
(probably we will continue the discussion on this old issue https://bugreports.qt.io/browse/PYSIDE-962 )

**Comment by Sclafus** [comment]
That's amazing! I will keep my eyes pealed on the next Qt and PySide versions, I hope to see this feature soon since it would be very interesting to see a Qt application written in Python as a web application! Thanks for the inside look from PySide @cmaureir !

**Comment by marimeireles** [comment]
Thanks @cmaureir :)
I caught up with the team and the resolution for this kind of issue right now is to open an issue upstream on pyodide asking them to have a look at your specific problem.
It seems like right now the only answer to this kind of request it's a case by case look.
But we're looking into different alternatives to make the use of non pure python libs better. =)
If you have any input, you're welcome to share!

**Comment by Sclafus** [comment]
There's already an issue open about Qt bindings in python with pyodide, if anyone is interested, check out [#1933](https://github.com/pyodide/pyodide/issues/1933)

**Comment by shaunroselt** [comment]
How about [FireMonkey (FMX)](https://github.com/Embarcadero/DelphiFMX4Python.git)?

I would love to be able to make my whole web interface with FMX for the browser too. That would be amazing.
