### ISSUE TITLE
[DOC] Development Story in documentation

### ISSUE THREAD

**Issue by amitsaha** [pyscript/pyscript#313]
**Is your feature request related to a problem? Please describe.**

It's still early days for PyScript, but it's important I believe (and I am sure i am not sharing anything earth shattering) to have an issue describing this. As a developer, I would need guidance around how I write my code - what editor do I use, how should I format my Python code inside `<pyscript></pyscript`>, how do I debug my code and write automated test for my code when targeting a *pyscript* deployment. 

The browser as an environment lowers the barrier for *running* my Python program, but it introduces challenges to the development process. Things that I have taken for granted when writing Python code such as debugging via `pdb`, writing and running unit tests - how do they translate to `pyscript`? Will inserting `pdb.set_trace()` work? If not, what's the alternative? I could scatter my code with `print()` statements - a perfectly reasonable strategy i think. But is that the only option? 

**Describe the solution you'd like**

A documentation section(s) addressing the above and proposing how one would go about doing the above tasks.

**Describe alternatives you've considered**

Not any.

**Additional context**

Related issue: https://github.com/pyscript/pyscript/issues/304

**Comment by antocuni** [comment]
Thanks for the report, I 100% agree that we need better docs.
We will certainly add new tutorials and improve the existing docs in the near future; but, at the same time, contributions are welcome :)

**Comment by SebastianOpiyo** [comment]
Hi, I would love to dedicate my time and help with this. All I need Is a little guidance. Thanks

**Comment by marimeireles** [comment]
Hey @amitsaha thank you for opening this issue.

>The browser as an environment lowers the barrier for running my Python program, but it introduces challenges to the development process. Things that I have taken for granted when writing Python code such as debugging via pdb, writing and running unit tests - how do they translate to pyscript? Will inserting pdb.set_trace() work? If not, what's the alternative? I could scatter my code with print() statements - a perfectly reasonable strategy i think. But is that the only option?

Yes, you're absolutely right. Many things we used to take for granted are currently not possible with pyscript.
Using the debug is one of them. The lack of an unified solution for files system, I/O and requests are some other examples.

I appreciate your input here but this is a very broad issue, so I'm closing it because we currently have more specific issues about what to add on the docs. 

But it's great to hear these perspectives. Thanks for the issue.

@SebastianOpiyo please take a look at the issues labeled as `docs` if you want to contribute :)
If you feel like they don't have enough information feel free to ping me with questions, we'd love to have more contributions on documentation!
