### ISSUE TITLE
[BUG] Facing Problem when Using requests Module

### ISSUE THREAD

**Issue by Veeresh-R-G** [pyscript/pyscript#319]
Ok so, right now I am using requests to a Pokemon API using the **request** Module in python.

The following error is been encountered several times !!
Anything with **https://** produces a “Can’t connect to HTTPS URL because the SSL module is not available.” error.

The code is working fine when I run it on the CLI ( windows Powershell)

Below is my Code:
` <py-env>
      - requests
    </py-env>`

    <div class="parent border-red-200 border-2 text-center align-center p-24 text-xl uppercase">
      <py-script src="./code.py">
        import requests
        req_pokiName = input("")
        API_CALL = "https://pokeapi.co/api/v2/pokemon/" + req_pokiName

        print(f"The Pokemon's Name is {req_pokiName}")
        RES = requests.get(API_CALL)
       </py-script>
    </div>   

**Screenshots**

**Comment by philippjfr** [comment]
Thanks for the issue @Veeresh-R-G . As noted in #91 pyodide does not yet support requests or in fact urllib3 because the entire networking stack does not translate to a browser environment very well. This is something we are looking at but you can also track similar issues on the pyodide repo: pyodide/pyodide#398

In the meantime I would recommend looking at the `pyodide.http` module (see https://pyodide.org/en/stable/usage/api/python-api.html), specifically the `pyfetch` and `open_url` function.

**Comment by Veeresh-R-G** [comment]
@philippjfr Thanks for resolving my query !!! 
Thanks a lot for stating alternative resources. Appreciate it !!!!🙃
