### ISSUE TITLE
[FEATURE] Use `script` tag instead of custom `py-script`

### ISSUE THREAD

**Issue by piranna** [pyscript/pyscript#329]
HTML `<script>` tag already supports to be used to host other languages than Javascript, with the [type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-type) or [language](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-language) attributes, so there's no need to use a custom `<py-script>` tag. Replace `<py-script>` tag with standard `<script>` one, or at least add support to use both of them.

**Comment by pnhearer** [comment]
So, I'm fishing out of my depth here but IANA is the standard. I searched for .py and .pyc and found nothing. Isn't this bug report just for debian? is this something OS specific or? 

IANA doesn't have anything for python
https://www.iana.org/assignments/media-types/media-types.xhtml?msclkid=ed29a333d13b11eca7a31995b9ae32f0

**Comment by pzwang** [comment]
PyScript is about making the web and Python super easy for everyone to use (not just experienced devs).  The fact that `<py-script>` is fewer characters is not merely a convenience; it is a fundamental part of the design philosophy.  Also, it fits idiomatically with the other tags/webcomponents that we have or will introduce, such as `py-repl`, `py-env`, `py-data`, etc.

On a very practical level, what are the steps involved to registering handlers for non-standard MIME types, across all browsers and platforms where the `<py-script>` tag currently works?  Unless someone can demonstrate that those steps are (1) as universal and functional as the current tag, and (2) as easy to use for beginners and casual programmers, then this is a non-starter.

**Comment by pnhearer** [comment]
I get the idea of making it easy for everyone which is why I'd advocate for using the <script> tag because it is already standardized. If someone picks some form of training to use html, this script tag is already familiar and is already standardized to accommodate scripting languages. Adding the extra tag(s) seems unobvious. Do you want; following the paradigm to encourage adoption or following the philosophy.

**Comment by pzwang** [comment]
There are WAY more characters to mistype and screw up in `<script type="blah">`, especially if that has to get typed *every single time* the user wants to punch in some Python code in the HTML.

> The application to register the MIME lives here.

Once a MIME type is registered, what is the process for browsers to handle it?

**Comment by pnhearer** [comment]
Sure there are more characters, I can't disagree. It is also an extremely easy thing to fix. Html isn't compiled. You can find a fix the issue from a plethora of places. No disrespect but I think this position is insulting to the intelligence of the average person. Editing a html tag is well within the grasp of an average person.

**Comment by pzwang** [comment]
> No disrespect but I think this position is insulting to the intelligence of the average person. Editing a html tag is well within the grasp of an average person.

I don't question that the average person can edit HTML tags - that's why PyScript leverage HTML. :-)
However, coming from a background of teaching Python and computers to many, many non-programmer types, it is my experience that every single additional character, symbol, etc. is a rock in their shoe.  Especially if this is something that has to get typed repeatedly in various sections of the HTML.  If the `<script>` tag were only to appear once, in the `<head>`, then that'd be one thing.  But it has to appear every single time that a user wants to insert some Python.  This could be in the event handler of a button.  This could be within some snippet of d3.  Every. Single. Place. has to now expand to a much more verbose, more error-prone pile of text.  And if the user mistypes it?  `<script type="python">` or `<script type="text/python">` instead of `<script type="text/x-python">`?  Then our JS preprocessor will silently ignore it, and the user won't understand why their thing didn't work.

And none of this removes the fact that there will be `<py-repl>`, `<py-ui>`, and may other kinds of tags within the PyScript framework.

I really don't understand what the hang-up is.  WebComponents are a standard part of HTML.  Angular and many other frameworks define their own tag.  Why can't PyScript?

**Comment by pzwang** [comment]
>  Also, there's no incompatibility on allowing both ways to define the scripts, using <script> or <py-script>.

There should be one obvious way to do it.

Adding two paths now means twice as many things to test on every single browser on every single platform.
What if some mobile browser decides to lock down 3rd party MIME plugin processing? What if some semantics change about the order of processing of <script> tags? etc. etc. etc.

YAGNI. One obvious way. Support that single way, test that single way. Invest energy elsewhere that adds value for users.

**Comment by antocuni** [comment]
Thank peter for the summary. I admit that the first thing which I though the first time I saw pyscript was exactly "why can't you use `<script>`?".

But after thinking about it, I came to the conclusion that `<py-script>` is by far less error prone than script. Apart begin easier to type, consider this case:
```html
  <body>
    <h1>hello</h1>
    <script type="python">print('hello from python')</script>
  </body>
```

Here I used `python` instead of `text/x-python` by mistake, and what happens is that the browser completely ignores the block. No error message, nothing printed on the screen.
With custom tags, if you do a typo, you get the source code printed in the HTML, so you can easily realize that something is going wrong.

That said, I think that the core team is well convinced to use `<py-script>`, unless there are compelling technical reasons to do otherwise. If it's just a stylistic or philosophical issue, I guess it's perfectly fine to disagree but at the end of the day we need to take a decision, and the decision was taken :).

@piranna, @pnhearer I'm closing this as `wontfix`, but feel free to reopen it if you think there is more to discuss. Thank you for bringing up the topic, I think it helped a lot to clarify our minds and to explain better the reasoning behind it!

**Comment by piranna** [comment]
> And none of this removes the fact that there will be `<py-repl>`, `<py-ui>`, and may other kinds of tags within the PyScript framework.
> 
> I really don't understand what the hang-up is. WebComponents are a standard part of HTML. Angular and many other frameworks define their own tag. Why can't PyScript?

Because that's not a WebComponent, that's a new script language. By using WebComponents to do that, you are using the wrong tool to fix the wrong problem on beforehand. Maybe the `<py-repl>` and `<py-ui>` tags, being UI components, can make more sense, but for code no.

> @piranna, @pnhearer I'm closing this as `wontfix`, but feel free to reopen it if you think there is more to discuss. Thank you for bringing up the topic, I think it helped a lot to clarify our minds and to explain better the reasoning behind it!

And that kids, is the difference between a serious proposal and a pet project.
