### ISSUE TITLE
Does it support importing "PYD" files?

### ISSUE THREAD

**Issue by zhorsex** [pyscript/pyscript#346]
As mentioned in the title, does "pyscript" support importing "PYD" module? If so, it will better protect the source code of web application.

**Comment by verhulstm** [comment]
i don't know if it is a supported feature.

but, i would recommend against it.

i understand in some use cases one might want to obscure code. but this is the opposite of some of the goals of this project.

one of our goals is to help to encourage apps to be made in such a way that anyone can "view source" and see working readable code. so we don't want to encourage a proliferation of obscure or hidden or minimized user-facing code. 

we want to encourage many users who might not have much experience to dig in and see how the code for the apps they are using are actually working "behind the scenes"

**Comment by antocuni** [comment]
On windows, `.pyd` files are basically DLLs and are generated by non-pure python extensions, e.g. if they are written in C.
At the current state, non-pure python extensions *are* supported by pyscript, but only if they are [included in pyodide](https://pyodide.org/en/stable/usage/packages-in-pyodide.html).

Closing as wontfix because `.pyd` files contain executable code which is specific to the operating system and the specific CPU. There is no chance they will ever work in the browser.
