### ISSUE TITLE
[FEATURE] Support a requests-like option for PyScript

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#364]
Requests doesn't work for upstream reasons (see #91 or https://github.com/pyodide/pyodide/issues/398 ) but, at the same time, is extremely popular and large part of PyScript users come with the expectations that it should just work. 

While the work to support this upstream is being done, I think it'd make sense for us to support this with a shim module that mimics the requests API as much as possible so that users can have an "easy" options instead of having to come up with creative solutions. 

[Requests API for reference.](https://docs.python-requests.org/en/latest/api/#module-requests)

**Comment by emirkmo** [comment]
Can you link the correct (draft) branch in this issue somewhere?

**Comment by emirkmo** [comment]
Got it. I got confused about what was being worked on non-publicly or not. I’ll take a crack at this soon. I think everything but the path-dependent parameters should be simple.

**Comment by emirkmo** [comment]
Hi @fpliger, I forgot about our conversation, but would this make more sense in upstream pyodide? 

See https://github.com/pyodide/pyodide/issues/3160

If not, then I could add it here. I did in fact shim my own for fun, so it should be relatively simple to get it running.

The `requests.py` inside [/pyscriptjs/src](https://github.com/pyscript/pyscript/tree/main/pyscriptjs/src) could then simply import and provide the request API from pyodide.

What do you think? Or is it better to have it downstream in pyscript since other back ends are (eventually) possible?

**Comment by fpliger** [comment]
Closing this since we can now use [pyodide-http](https://github.com/koenvo/pyodide-http)
