### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by Shahin-rmz** [pyscript/pyscript#421]
Hello,
I really love the idea behind this project. It solves one of the fields that we lack in Python.
being able to write in front end .
How ever, I want to know how can I start to write real program with pyscript.
I am by no meens full time deveoper, just an occasional developer. I would be happy if I can contribute by testing and using the pyscrpt.
But when it will be functionally in alpha or beta version?
I can see the project is really getting noticed, but can't guess about time.
1 month? 1 year?

**Comment by Siddharth1India** [comment]
Many people already started using PyScript to create projects. 
I am using alpha version of to create real project. If you think there can be some PR which can make your project useless than I suggest you to clone repo, download code and use it locally.
It will of course take time because it is launched less than one month back but Python community is huge so it will be fast progress.
Also, talking about time, it depends on how fast people started using it at large scale. Significantly big community for PyScript will take this project to real usages.
