### ISSUE TITLE
我用的是IDEA工具使用JSP工程，导入link和script包之后可是无法使用pyscript[BUG]

### ISSUE THREAD

**Issue by yishiwuchu** [pyscript/pyscript#456]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: either a code snippet or a link to an HTML page which shows the bug.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by philippjfr** [comment]
@yishiwuchu It looks like you forgot to provide any details on the issue form. Please edit the issue with a description of the bug you are experiencing.

**Comment by sai-nallani** [comment]
Yea I have a similar bug. I linked the source code with 
```
<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css"/>
<script defer src="https://pyscript.net/alpha/pyscript.js"></script>
```
![image](https://user-images.githubusercontent.com/74580408/170120645-b805e872-26c1-4593-8c8c-969cfba16c45.png)

**Comment by marimeireles** [comment]
It seems like your issue is related to the way you're dealing with imports. Please check: https://github.com/pyscript/pyscript/blob/main/docs/tutorials/getting-started.md. This doesn't seem like a real bug.
If the problem persists please open a detailed issue. You can use google translator or similar tool and I'm sure that with a bit of effort from both sides we'll be able to understand each other. ;)
