### ISSUE TITLE
Bug (maybe Security related)

### ISSUE THREAD

**Issue by Network-Sec** [pyscript/pyscript#509]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Try in https://pyscript.net/examples/repl.html
import sys
sys.stdout.buffer.write(b'0a')

Returns information disclosure / source code backtrace 

containing multiple eval() statements. 

Didn't explore further, hope it helps to may Pyscript more secure. Great project!

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by nmstoker** [comment]
@Network-Sec i think it might help if you spell out your concerns here as it doesn't seem that obvious what the problem is.

Also, I'm not sure if you're aware but the locations given in the tracebacks will be from within the browser sandbox, not from the local PC, so it's not likely to cause much concern usually.

**Comment by marimeireles** [comment]
For further info. on how WASM works: https://webassembly.org/docs/security/#:~:text=The%20security%20model%20of%20WebAssembly,the%20constraints%20of%20(1).
This may address your worries on security.

**Comment by marimeireles** [comment]
Closing as inactive.
Feel free to re-open if you still think we have an issue here.
Thanks for the input.
