### ISSUE TITLE
Console printing is not rended on the page if there is an expensive process running

### ISSUE THREAD

**Issue by adilaxmdv** [pyscript/pyscript#529]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

```

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <title>PyScript Hello World</title>

    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />

    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  </head>

  <body>
    <py-script>
while True:
      print("PyScript")
  </py-script>
  </body>
</html>

```

Browser is overwhelmed by PyScript execution and it's not able to render `print` statements to the screen, that by default are console outputs.

We might want to have something like <py-script output="__auto__"> or something to allow users to render output on the page.

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Additional Context

Playscript should this type while loop eternity show or cancel

**Comment by marimeireles** [comment]
Interesting catch!
On my FF the browser kind of crashes.
The page is loading for ever and doesn't open devtools or anything like that.
Thanks for reporting.

**Comment by rodjunger** [comment]
An infinite loop is a bug in your code, not in pyscript. If you do the same thing with javascript (or any language to be precise) your browser will eventually hang and crash too, I don't see how this is an issue. This is a self-DOS issue and the fix is to not write bad code.

**Comment by marimeireles** [comment]
What I thought it was weird was that my page doesn't render anything.
If I do the following:

```
    <py-script>
print('👽')

while True:
  print(':D')
    </py-script>
```

The page doesn't render nor print the emoji, it just goes straight to working on the `while`... I can't explain this behavior. @fpliger probably can, tho :)

**Comment by RaSan147** [comment]
🤔does it run the code first (behind the loading framework screen) and shows us output at once, since 👽 emoji should at least print if things are moving runtime side by side

**Comment by fpliger** [comment]
It seems like a bug with the `<py-script>` output... or maybe room for improvement. It does print output to the console for me but it's too verbose of an output. We should improve it.

I'm not sure I agree with the fact that the page should render something (we need a UX design decision on that). By default the output is the console not a div but we should better document it and actually decide/design better. If the console is the default output, we should also have something like `<py-script output="__auto__">`  or something to allow users to render output on the page

That said, the example itself doesn't help though because an infinite loop printing something can quickly overwhelm the output or make a browser crash, as @marimeireles  pointed out :)

**Comment by marimeireles** [comment]
I see, thanks for chiming in @fpliger :)

**Comment by marimeireles** [comment]
I'm closing this as this is an inherit behavior of the browser.
This will be fixed once we finish the implementation of webworkers which will allow multiple expensive computations run on multiple loops =)
