### ISSUE TITLE
Refused to load the script violates Content Security Policy

### ISSUE THREAD

**Issue by ch3njust1n** [pyscript/pyscript#575]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I only added the following lines and my browser refused to load the script

```
<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
<script defer src="https://pyscript.net/alpha/pyscript.js"></script>
```

![Screen Shot 2022-07-06 at 12 43 54 PM](https://user-images.githubusercontent.com/3211697/177601992-0d00baf6-5ba7-4b47-ae8a-57855f5f4450.png)

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
Refused to load the script 'https://pyscript.net/alpha/pyscript.js' because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by JeffersGlass** [comment]
It sounds like either the server you're using to serve the files in question, or the framework you're working in, is adding a [Content Security Policy](https://csper.io/blog/csp-violates-the-content-security-policy-directive) that is blocking your page from loading Javascript from external sources.

I would look at the resources for your server (or dev server) for information about adjusting the CSP rules, or barring that, see if the page or framework includes any [<meta> directives that reference CSPs](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP), something like: `<meta http-equiv="Content-Security-Policy" srcript-src = 'self' ... >

[This StackOverflow answer](https://stackoverflow.com/questions/34950009/chrome-extension-refused-to-load-the-script-because-it-violates-the-following-c) has a variety of ways of addressing CSP issues in various contexts.
