### ISSUE TITLE
scapy and mysql.connector python libraries do not work with pyscript

### ISSUE THREAD

**Issue by Jonathan70852** [pyscript/pyscript#619]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

I am trying to use the scapy and mysql.connector libraries in pyscript but it always gives me the error that it does not find any module with those names.
I need help please.

        
        <head>
        
        <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
        <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
        
        </head>
        <body>
        <py-env>
            scapy
            mysql.connector
            
        </py-env>
            <py-script> 
           
        from os import remove
        from scapy.all import *
        from time import time
        import csv
        import mysql.connector
        from browser import alert, document
        
        
            </py-script>
        
        </body>
        </html>

and I always get the same error: 

JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 2, in ModuleNotFoundError: No module named 'scapy' )

**Comment by JeffersGlass** [comment]
If you [open your browser's developer console](https://appuals.com/open-browser-console/), you may see an error like  `ValueError: Couldn't find a pure Python 3 wheel for 'scapy'. You can use micropip.install(..., keep_going=True) to get a list of all packages with missing wheels.` At least that's what I see when I try to load scapy.

The reason for this error is that micropip (which the Pyodide python distribution [uses to install packages](https://pyodide.org/en/stable/usage/loading-packages.html)) only works with packages that have pure Python wheels on PyPI. Since [scapy on PyPI](https://pypi.org/project/scapy/#description) only provides a source tarball, micropip fails to load it.

That said, it seems the included source tarball looks like it's built to use [setuptools](https://pythonhosted.org/an_example_pypi_project/setuptools.html), so you may be able to build your own wheel and import that?

All that said, I'd be a little surprised if scapy worked out of the box in the browser - Pyscript/pyodide doesn't have access to sockets, packets, or the network layer, so receiving/sending packets I suspect will fail? Maybe for packet analysis though?

**Comment by archsr** [comment]
I have similar issue with respect to mysql-connector. I see the following error. Is there any temporary resolution for the same?
`ValueError: Couldn't find a pure Python 3 wheel for 'mysql-connector'. You can use `micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.`

**Comment by JeffersGlass** [comment]
@archsr I'm not super familiar with that package, but assuming it's [this MySQL Connector](https://dev.mysql.com/doc/connector-python/en/), its name on PyPI is [mysql-connector-python](https://dev.mysql.com/doc/connector-python/en/connector-python-installation-binary.html). That will resolve the micropip issue:

```html
<py-env>
  - mysql-connector-python
<py-env>

<py-script>
import mysql.connector
...
</py-script>
```

However, the ssl module is currently in early development stages in Pyodide, so the package still fails to load - see issue #381 in this repository, and the [upstream development work in Pyodide #529](https://github.com/pyodide/pyodide/issues/529).

**Comment by archsr** [comment]
@JeffersGlass You are correct, I now see ssl module error.

`Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 2, in <module>
  File "/lib/python3.10/site-packages/mysql/connector/__init__.py", line 53, in <module>
    from .connection import MySQLConnection
  File "/lib/python3.10/site-packages/mysql/connector/connection.py", line 44, in <module>
    from .constants import (
  File "/lib/python3.10/site-packages/mysql/connector/constants.py", line 32, in <module>
    import ssl
  File "/lib/python3.10/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'`

**Comment by archsr** [comment]
Jut went through the issue #381 So no possible way to use mysql a this point due to security limitations.

**Comment by JeffersGlass** [comment]
Agreed - believe this can be closed as _wontfix_ or perhaps _wontfix-upstream_.

**Comment by mohamedk314** [comment]
now i have the same problem that i cannot use scapy with pystream is there any solution or any replacement ?
