### ISSUE TITLE
[622] py-script should only render to the page through the `display` function

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#635]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

In order to disambiguate debugging output and rendering to the page, we want to add a new `display` function that can be called explicitly whenever the user wants to render things on the page. See more details at #622

### Why is this needed

Se #622

### What should happen?

We will introduce a new method `display` that can be used to display objects and other things on the page.

Here's the proposed method:

```python
def display(*objects, parent=None):
    """Display `objects` on parent. 

All non-keyword arguments are converted using the global renderer mapper or using the object `__repr__` if a renderer for that object is not present. 

If `parent` is None, the parent object set at the global `py-script` tag level will be used. 
    """
```

**Comment by SkriiL** [comment]
Sorry for the commit spam. Should not include the issue number in the commit message next time.
Is there a way i can unlink them from the issue?

**Comment by JeffersGlass** [comment]
A couple of edge details I'd propose:

## Exceptions

### Exceptions Should Show Up Onscreen

I'd propose that if an object fails to render (e.g. if an exception is raised when processing the object through the rendered mapper, or in the objet's __repr__, etc) that _something_ still be rendered to the DOM in the specified location. Since the intent is to present objects onscreen, failure's should be visible to the user onscreen. This _something_ should ideally include the Exception message.

I'd propose that if Exceptions in general are being output to the console, then errors during display() should also be output to the console, in addition to being displayed onscreen in some way.

#### Exception Formatting
Optional Extra Idea: this opens the door to a parameter that changes this behavior. Perhaps a parameter called `error_handler`, with default value None, which takes a callable. If error_handler is not None, if an exception `exc` is raised during display(), what's printed to the screen is not the (formatted?) trace of the error itself, but the results of `error_handler(exc)`. The error-handler parameter is set equal to the error-handler attribute on the associated tag, if it exists.

This allows advanced users to customize the behavior when errors occur. This would also allow users to suppress output of display() errors by setting `error_handler = lambda x: None`. We can flesh out further details if this feels like an interesting path.

### When `parent` is None

A question about the details of this:

> If `parent` is None, the parent object set at the global `py-script` tag level will be used. 

I take this to mean that, if no parent is provided, the object is displayed as a child of the <py-script> tag's parent in the DOM? This seems like a decent option, and I'd propose that:
- The first time display(...parent=None) is called in a <py-script>tag, the object is rendered as the next sibling of that <py-script> tag
- All subsequent calls in that tag where parent is None should render objects as the next sibling _of the previous object_ rendered this way.

Just another way of saying that:
```python
<p>an introduction</p>
<py-script>
    display("this is my first thought")
    display("and this is a second thought")
    display("i thought of a footnote", parent = Element("footnote"))
    display("also, a third thought")
</py-script>
<p>my closing thoughts</p>
<p id="footnote"></p>
```
Should render as:
![image](https://user-images.githubusercontent.com/1931111/183143277-8a40968f-32c1-42cb-bc1a-24b21420530f.png)
Maybe that seemed self-evident, but I thought it'd be worth specifying.

**Comment by antocuni** [comment]
> ### Exceptions in Display Should Show Up Onscreen
> I'd propose that if an object fails to render (e.g. if an exception is raised when processing the object through the rendered mapper, or in the objet's **repr**, etc) that _something_ still be rendered to the DOM in the specified location. Since the intent is to present objects onscreen, failure's should be visible to the user onscreen. This _something_ should ideally include the Exception message.

I agree, exceptions should not be silent. Although this is probably an discussion which is orthogonal from this particular issue and should probably be discussed elsewhere.

> I'd propose that if Exceptions in general are being output to the console, then errors during display() should also be output to the console, in addition to being displayed onscreen in some way.

I would make it even more extreme and propose that exception should _never_ be silent, even if they are raised outside a `display()` call.

> #### Exception Formatting
> Optional Extra Idea: this opens the door to a parameter that changes this behavior. Perhaps a parameter called `error_handler`, with default value None, which takes a callable. If error_handler is not None, if an exception `exc` is raised during display(), what's output to the screen is not the (formatted?) trace of the error itself, but the results of `error_handler(exc)`. The error-handler parameter is set equal to the error-handler attribute on the associated tag, if it exists.
> 
> This allows advanced users to customize the behavior when errors occur. This would also allow users to suppress output of display() errors by setting `error_handler = lambda x: None`. We can flesh out further details if this feels like an interesting path.

I like the idea. Probably we can extend it to have also a per-page error handler. I.e.:

1. there is a page-level `error_handler`
2. individual `<py-script>` tags can override `error_handler` if they want
3. the default page-level `error_handler` displays the exception as a node in the DOM
4. you can suppress exception reporting by overriding `error_handler` (either at the page level or the tag level).

This design has also the bonus point of being very similar to what python itself uses to display errors in the REPL, i.e. `sys.excepthook`:
```
>>> import sys
>>> sys.excepthook = lambda etype, eval, tb: None
>>> raise Exception('hello')
>>>
```

> ### When `parent` is None
> A question about the details of this:
> 
> > If `parent` is None, the parent object set at the global `py-script` tag level will be used.
> 
> I take this to mean that, if no parent is provided, the object is displayed as the next sibling of the tag's parent in the DOM? This seems like a decent option, and I'd propose that:

yes, I think it's a good idea and a reasonable default.


> * The first time display(...parent=None) is called in a tag, the object is rendered as the next sibling of that  tag
> * All subsequent calls in that tag where parent is None should render objects as the next sibling _of the previous object_ rendered this way.
[cut]
> Maybe that seemed self-evident, but I thought it'd be worth specifying.

I agree with this. And it's a good idea to be explicit, thanks :)

> **Edit: I've realized baked into that image is the assumption that consecutive display() calls output on separate lines (separate `<p>` tags? separate `<div>`s as currently?). Perhaps that's not right... the issues referenced in the parent issue are almost all about how print() renders consecutive outputs on different lines...**

I think that every call to `display()` should insert its own HTML tag. Which tag depends on the object being displayed:
- `display('some string')` (and other simple objects) should probably insert something like `<div class="pyscript-text">some string</div>`, to make it possible to apply a CSS style to it
- most "rich" objects (e.g. plots, dataframes, images, etc.) will have a custom renderer which generates some complex HTML.

**Comment by antocuni** [comment]
@marimeireles you closed this as completed but it's not true :)
`print()` still displays something in the DOM, while it shouldn't.
Try to run e.g. this test and you will see that "hello world" is displayed in the page:
```python
    def test_print(self):
        self.pyscript_run(
            """
            <py-script>
                print('hello world')
            </py-script>
            """
        )
```

**Comment by antocuni** [comment]
Sorry, I made a mistake and I was running pyscript on the wrong branch. I confirm that this issue is fully resolved, closing it again.
