### ISSUE TITLE
Python Built-in function "type" doesn't work

### ISSUE THREAD

**Issue by nwatab** [pyscript/pyscript#667]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

1. Go to https://pyscript.net/examples/repl.html
2. Write "type(1)" in a <pr-repl></pr-repl> cell
3. Execute
4. No output is shown

Instead, <class 'int'> should be shown as an output.

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
evaluate 2pyodide.asm.js:14
----> changed out to my-repl-1 true pyodide.asm.js:14
----> changed out to my-repl-1 true pyodide.asm.js:14
----> changed out to undefined true 2pyodide.asm.js:14
----> reverted pyodide.asm.js:14
----> reverted pyodide.asm.js:14
Element.write: <class 'int'>
--> True pyodide.asm.js:14
APPENDING: True ==> my-repl-1
--> <class 'int'> pyrepl.ts:142
connected pyrepl.ts:142 connected
```

**Comment by JeffersGlass** [comment]
The short answer is: There's a large overhaul happening to how Pyscript handles rendering to the screen vs outputting to the console (#662), so I expect issues like this to be subsumed into that overhaul.

To address this specifically: this is an open issue with how Pyscript outputs from REPLs - the output is interpreted as HTML, and the browser interprets `<class 'int'>` to be an HTML tag it doesn't know about, and therefore displays nothing. See for example #347.

![image](https://user-images.githubusercontent.com/1931111/183122612-aaf330bb-47f2-402a-911b-b3cce0e7845a.png)

You can see that Python is generating the correct result (i.e. the issue is in Pyscript's output process) by doing something like:
```python
>>> list(str(type(1)))
['<', 'c', 'l', 'a', 's', 's', ' ', "'", 'i', 'n', 't', "'", '>']
```
![image](https://user-images.githubusercontent.com/1931111/183122748-4ee4ae21-95c6-47de-9f1e-eb43a824c9e2.png)

**Comment by nwatab** [comment]
@JeffersGlass 
Thanks! The problem is clear now. Just out of curiosity, why don't you convert a standard output into string to show an output as it is on python side?

I came across another similar problem (I'm refraining to create multiple issues). When you type 0.1 + 0.9 in py-repl, the output shows 1, instead of 1.0. I assume it is because javascript interprets 1.0 as 1.

**Comment by JeffersGlass** [comment]
> I came across another similar problem (I'm refraining to create multiple issues). When you type 0.1 + 0.9 in py-repl, the output shows 1, instead of 1.0. I assume it is because javascript interprets 1.0 as 1.

While I can't speak directly to your first question, your thoughts about the second question are spot-on. By default, \<py-repl\> (and  all the executable tags, including \<py-script\>) return the value of the final expression to the javascript function `pyodide.runPython()`.... PyScript then puts this output on the screen. And because JS only has one number type, it outputs 1.0 as `1`. 

This is a genuine bug, and probably something worth fixing in the I/O overhaul. Want to open a new issue for it?

**Comment by JeffersGlass** [comment]
For what it's worth, you can disable the behavior of outputting the final expression, if you want, by ending the final line with a semicolon, which is sometimes useful if your final line is a function that you're using for its side effects but also returns a value. (Not sure why'd you want that in a REPL, but useful in scripts). A silly example:

```python
<py-script>
  def add_print_and_return(a, b):
      print(f"{a + b = }")
      return a + b
  
  add_print_and_return(1, 2)
</py-script>
```

```python 
# In browser:
a + b = 3
3
```

To hide the final '3', you can add a semicolon to the end of the final line: `add_print_and_return(1, 2);`.

I've mostly run into this when adding new html elements to the DOM, since [Node.appendChild()](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild) returns the newly created node. So if you do something like:

```python
from js import document
new_p = document.createElement("p")
new_p.innerText="Hello, world!"
document.body.appendChild(new_p)
```
You get:
```
[object HTMLParagraphElement]
Hello, world!
```
Again, adding the semicolon hides the stray returned object.

**Comment by nwatab** [comment]
@JeffersGlass 
Thanks for the detailed explanation. Yes, it's worthwhile to fix the I/O. It would be nice if you could customize the output from python on python side before passing it to javascript. I'm making a python tutorial website, and it will have few interactions between python and javascript. I'm thinking to create a simple wrapper of py

Thanks for clarification of the semicolon at the end of lines. I didn't know that.

**Comment by zeki07k** [comment]
> 

Why I can't use **from js import document** line?
My python script doesnt accept it .
**Script**:


from dimension import Dimension
from js import document


class Board(Dimension):
    BLACK_CELL = "blackCell"
    WHITE_CELL = "white_cell"

    def __init__(self, width, height):
        super().__init__(width, height)

    def create_html_element(self):
        dimension_size = self.height
        table = document.createElement('table')
        for row in range(dimension_size):
            tr = document.createElement('tr')
            for col in range(dimension_size):
                td = document.createElement('td')
                if (row % 2 == col % 2):
                    td.classList.add(self.WHITE_CELL)
                else:
                    td.classList.add(self.BLACK_CELL)
                tr.appendChild(td)
            table.appendChild(tr)
        document.body.appendChild(table)

**Comment by JeffersGlass** [comment]
@zeki07k Probably best to open a new issue rather than adding to this one.

What's the context of running this script? A <py-script> tag on the page? Imported from another file? Running locally?

**Comment by zeki07k** [comment]
I will call mainçpy file via that script:
main.py:
```
from chessBoard.board import Board


def main(width, height):
    board = Board(width, height)
    board.create_html_element()


if __name__ == "main":
    main(8, 8)**

```
then I will put into html file like this.
```
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<style>
    body {
        background-color: white;
    }
    .blackCell {
        background-color: black;
        width: 30px;
        height: 30px;
    }
    .whiteCell {
        background-color: white;
        width: 30px;
        height: 30px;
    }
    table {
        border: 3px solid blue;
        width: 270px;
    }
</style>
<table id="board">

</table>

<py-script>

    src="./chess/main/main.py"
</py-script>
</body>
</html>
```

**Comment by tedpatrick** [comment]
Your example is pointed at the alpha release of PyScript which depends on an older version of Pyodide.

alpha
```html
<link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
<script defer src="https://pyscript.net/alpha/pyscript.js"></script>
```

latest
```html
<link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
<script defer src="https://pyscript.net/latest/pyscript.js"></script>
```

unstable
```html
<link rel="stylesheet" href="https://pyscript.net/unstable/pyscript.css" />
<script defer src="https://pyscript.net/unstable/pyscript.js"></script>
```

example using js module in `unstable`
```html
<html>
<head>
    <link rel="stylesheet" href="https://pyscript.net/unstable/pyscript.css" />
    <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
</head>
<body>
    <py-script>
import js

js.console.log( "Hello on JS Console" )
js.document.title = "FOO"
    </py-script>
</body>
</html>
```
