### ISSUE TITLE
Please make pyscript.js available via CDN

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyscript/pyscript#68]
In my context its much, much easier to use something like pyscript.js via a CDN than having to install and maintain node.js etc.

Furthermore the promise of web components and python in the browser is that you don't need all of the .js tooling.

Please provide pyscript.js via a CDN. Thanks.

**Comment by jezdez** [comment]
I believe this will be fixed with #66.

**Comment by AlbertDeFusco** [comment]
You can already be able to access the JS and CSS from pysript.net

```html
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
      <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  </head>
</html>
```

**Comment by MarcSkovMadsen** [comment]
Thanks @AlbertDeFusco . Unfortunately I cannot access that link from a "newly created web site" for enterprise security reasons.

Is there are an alternative github or cdn link?

**Comment by fpliger** [comment]
Thanks for the feedback @MarcSkovMadsen ! We'll be looking more at the release process during this very early and alpha phase in the next few days as we are also working on some automation (releases, nightly builds, etc..). This is relevant and will make sure we take that into account too. 👍

**Comment by marimeireles** [comment]
@MarcSkovMadsen I wonder if your problem is now solved?

**Comment by marimeireles** [comment]
We're having this discussion on https://github.com/pyscript/pyscript.net/issues/39
So.. Let's keep it there to keep it centralized. :)

**Comment by marimeireles** [comment]
Oh no, sorry I was confused, please ignore my last comment!
It's somewhat related but this one should be opened. I guess I could take up on this.
Is it okay if we host this here? https://github.com/cdnjs/packages
Any opinions?

**Comment by hemangjoshi37a** [comment]
@MarcSkovMadsen, I understand your need to access pyscript.js via a CDN rather than the provided link. Here's a potential solution to address your issue:

1. To make pyscript.js available through a more accessible CDN, we can submit a request to host the file on a popular CDN service like cdnjs (https://github.com/cdnjs/packages). This should help bypass the enterprise security restrictions you're facing.

2. Once the file is available on the chosen CDN, update the link in your project to use the new CDN URL for pyscript.js.

I hope this solution meets your requirements. If you have any questions or need further assistance, please let me know.

**Comment by WebReflection** [comment]
As explained in [most recent docs](https://pyscript.github.io/docs/2023.11.2/beginning-pyscript/#indexhtml) we currently work only out of a cdn:

```html
<link rel="stylesheet" href="https://pyscript.net/releases/2023.11.2/core.css">
<script type="module" src="https://pyscript.net/releases/2023.11.2/core.js"></script>
```

I think we can close this as this has been the case for a while.
