### ISSUE TITLE
Make it easy to display "loading" information

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyscript/pyscript#70]
Perceived speed of #dataapps is key. A user gets annoyed, uncertain and might leave your framework behind if the #dataapps seems stuck. I.e. when there is no indication of activity and the browser might even not be reacting. Its a bad user experience.

An example of a bad user experience is the `panel_kmeans` app loading experience.

Please make it very, very easy (or automatic) to display loading info to the user while pyscript.js, pyodide and python libraries are loading.

**Comment by AlbertDeFusco** [comment]
I agree. It's "fairly" easy now to build your own loading animation since tailwindcss is included in pyscript.css. I think it's certainly possible to automate the loader/spinner.

Here's a concept. View the source to see what I did. http://adefusco.pythonanywhere.com/

**Comment by giswqs** [comment]
It takes several seconds to load, and it seems the browser icon never stops sniping. I agree with @AlbertDeFusco, adding a animated loader/spinner would be nice. 

https://giswqs.github.io/pyscript-demo/

![Peek 2022-05-01 08-06](https://user-images.githubusercontent.com/5016453/166145125-430b0c68-cbda-43dc-aa08-1a34bb7fa541.gif)

**Comment by fpliger** [comment]
Closing #159 and keeping this one. 

We definitely need something like this. My proposal is to add an initial "default" component that will take care of showing a spinning circle (or something like that) until PyScript is done loading and executing the application code. If possible and doesn't add too much time/complexity, we should make it extensible so it's easy to overwrite the default behavior so that it can be customizible.
