### ISSUE TITLE
Relevant message when wrong file (through a typo or otherwise) accessed through a webserver

### ISSUE THREAD

**Issue by madhur-tandon** [pyscript/pyscript#876]
Details here: https://github.com/pyscript/pyscript/blob/0cfe20ca6529932669d48b09e985c8fc37d5090f/pyscriptjs/src/utils.ts#L67

**Comment by sgeisenh** [comment]
This looks like it may not be relevant anymore since `handleFetchError` is no longer in https://github.com/pyscript/pyscript/blob/main/pyscriptjs/src/utils.ts

Does the `robustFetch` implementation mostly address this issue?
https://github.com/pyscript/pyscript/blob/main/pyscriptjs/src/fetch.ts#L12-L57
