### ISSUE TITLE
display() sends the output to the wrong tag

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#878]
`<rant>`
During the infinite discussion in https://github.com/pyscript/pyscript/issues/769 we decided to use a "dynamic" implicit target for `display()`, which as far as I know can be only implemented with a global variable.

I am [still convinced](https://github.com/pyscript/pyscript/pull/749#discussion_r995734547) that this approach is very fragile and it will create tons of problems and nasty and subtle bugs.
I predict this is the first of many :crystal_ball:

We are still in time to change our minds.
`</rant>`

I found this problem during an unrelated refactoring. I think I know what happens but I don't want to solve it now, so I'm writing an issue to make sure we don't forget.
Consider this test:
```python
        self.pyscript_run(
            """
            <py-script>
                display('hello 1')
            </py-script>
            <p>hello 2</p>
            <py-script>
                display('hello 3')
            </py-script>
        """
        )
```

It displays `hello 2, hello 1, hello 3`:
![image](https://user-images.githubusercontent.com/344507/197330908-40190d49-749a-4d32-98d7-2ef321ae132f.png)

I think the bug was introduce by PR #749 but the roots of the bug are much deeper than this and shows some criticality on our code base.

To start with, the current test that we have is suboptimal:
https://github.com/pyscript/pyscript/blob/aa85f5f5964e61f47b77cac73511d3d74c63328d/pyscriptjs/tests/integration/test_02_output.py#L19-L38

it seems to test for the right thing, but because of the mess that we do when generating outputs, the test passes "by chance". The problem is that to display outputs we create `<div>`s inside `<div>`s inside `<div>`s, each with a random ID, which makes everything very hard to test. We should improve testability of such a simple thing. This will hopefully be solved as part of the PR I'm working on.

The other problem is much deeper. I *think* that the root cause is here:
https://github.com/pyscript/pyscript/blob/aa85f5f5964e61f47b77cac73511d3d74c63328d/pyscriptjs/src/components/base.ts#L119-L124

The thing to note is that `Runtime.run` is `async`, so the three calls are not executed in strict order. I think that what happens is roughly the following:
1. `main.ts` starts to execute the first py-script. We run `set_current_display_target(FIRST_TAG)`, but since it's `async` we immediately interrupt the execution
2. `main.ts` starts to execute the second py-scritp. We run `set_current_display_target(SECOND_TAG)`.
3. at some point in the future we execute the rest of the `run()`, but now the "current display target" is always `SECOND_TAG`.

The proper fix is to ensure that the three calls are done atomically, but it's very hard to to it reliably.
A quick&dirty fix is probably to concatenate the three strings into one big string, but it's a very slipper slope. It might work right now because we execute everything in the global namespace (and we shouldn't) and it will break as soon as we stop doing it (e.g. to implement custom namespaces).

Another "maybe fix" is to use the famous `ContextVar`, but AFAIK it's a python-only thing. I don't really know how it interacts with the JS event loop and I think we should be very cautious before using it without *fully* understanding how it works in pyodide.

Another possible fix is to use *synchronous* calls to `run`: this probably solves the problem, but it breaks all `py-script` tags which uses `await` at top level. FWIW, this is one more data point which indicates that maybe they should not be allowed.
Note that currently we don't have any way to run pyodide code synchronously, which should probably kill `Runtime.run` and introduce `Runtime.runSync` and `Runtime.runAsync`.

**Comment by JeffersGlass** [comment]
I can speak a bit to the use of how we could use a ContextVar to help solve some of these issues - based around the rough demo I hashed out while we were discussing display(). (The [source branch](https://github.com/JeffersGlass/pyscript/tree/output-contextvar) is of course behind, but still there.)

The ContextVar approach at its heart isn't actually so different from the global variable approach we have now. The current approach has a global variable with a setter and getter:

```python
get_current_display_target._id                  # global variable
def get_current_display_target(): ...           # getter
def set_current_display_target(target_id): ...  # setter
```

As a ContextVar, we still have a global variable with a getter and a setter:

```python
output_context = contextvars.ContextVar('output')       # global variable
output_context.get()                                    # getter
token = output_context.set()                            # setter, see note*
output_context.reset(token)                             # setter, see note*
```

But the advantages are:
1. Since the ContextVars are async-friendly, so long as `display()` uses `output_context.get()` to retrieve the ID it should be writing to, this works in async contexts.
2. `output_context.set()` returns a [Token](https://docs.python.org/3/library/contextvars.html#contextvars.Token) representing the previous or 'parent' context. This allows to to "pop" a context off the "stack" of contexts when we're done with it, as opposed to just resetting context to `None` when we're done.

**Note - because each context creates its own token, we need each token name to be unique in the namespace it's in, otherwise they overwrite each other. In my experiments, I'd defaulted to using a [GUID](https://github.com/JeffersGlass/pyscript/blob/a3b0f6711cd4943eac40f78700ba99f159079a73/pyscriptjs/src/utils.ts#L50-L54) for the token, but there may be a cleverer way.*

To be clear here - the ContextVar methods are meant to **replace**  `get_current_display_target()`, `set_current_display_target()` etc. The ContextVar isn't an argument to these functions, it is the new state/getter/setter system.

----

The question then becomes, "What causes us to enter/exit a new context?" and "what does that actually look like in code?"

My suggestion, based on [our discussions](https://github.com/pyscript/pyscript/issues/769#issuecomment-1248397214) in #769, is that the following `set()` a new context before executing python code and `reset()` it following:

-  A default display target set in `<py-config>` when pyscript.js initializes sets a context and never resets it. (Not sure anybody wants this but me 😅)
- `evaluate()`-ing any relevant tag, or, in the language of #881, `pyExec()` and `pyExecDontHandleErrors()`. Because those two functions are only called in the context of a tag, we can use either the ID of the tag or a relevant HTML attribute to determine the new context to create.
- Triggering any event via the `py-[event]` syntax. Again, because `py-[event]` attributes are associated with a specific tag, we can use that tag's ID to establish a context. (Though I know that syntax is being thoroughly rehashed, this may no longer be relevant.)

To set and reset a tag for each of these, we surround the source with `set()` and `reset()` with the relevant token:

```js
const tokenName = "token" + guidString()
source = `${tokenName} = output_context.set(relevent_tag_id);\n`
    + source
    + `\noutput_context_var.reset(${tokenName})`

...

runtime.runPythonAsync(source) // or runPython(source)
```

This works for either synchronous or async code:

 - If the code is synchronous, the user's source is wrapped by `set()` and `reset()`, so the code works in the only context it knows.
 - If the code is async:
    - If we're talking about instantiating/starting new coroutines via `async def` and something like `loop.create_task()`, `asyncio.gather()` etc, these default to using the enclosing context
    - If we're talking about top-level await (*though I agree we should kill it*), the coroutine compiled by runPythonAsync will contain both the `set()` and `reset()` calls from above, which will not bleed over into other coroutines.

> A quick&dirty fix is probably to concatenate the three strings into one big string, but it's a very slipper slope. It might work right now because we execute everything in the global namespace (and we shouldn't) and it will break as soon as we stop doing it (e.g. to implement custom namespaces)

I believe so long as the context Token lives in the same namespace as the source itself (and by concatenating sources, it must), this will continue to work.

**Comment by antocuni** [comment]
I don't think we can reliably use `ContextVar`.
See https://github.com/pyscript/pyscript/issues/879#issuecomment-1298643910 for more details.

**Comment by antocuni** [comment]
> Can't reproduce any of these problems anymore. I think we can safely close this one :)

Sorry, no :)
We had a bug which was not caught by any of the existing tests. Now apparently the bug has gone (probably as a by-product of some other change), but the only way to ensure that we won't reintroduce it again in the future is to add a proper test.
So the correct way to proceed is:
1. go back in the history to a commit whose date is similar to this issue (Oct 22; for example, aa85f5f)
2. write a proper test based on the example which I wrote in the first commet
3. *ensure that it fails*
4. update to the latest `main`
5. ensure that the test now passes
6. commit the test

I know it's a bit cumbersome but it's the only way to ensure that bugs won't return :man_shrugging:

**Comment by marimeireles** [comment]
I thought we were already doing that.
But alright, lemme check this ;)
