### ISSUE TITLE
PyScript should support more than on py-repl per page

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#893]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

As pointed out in #884, py-repl only support one instance per page. 

### Why is this needed

There are many scenarios where an user could want to use more than just one repl and we should support it.

### What should happen?

We should change https://github.com/pyscript/pyscript/blob/f9194cc833eb938800f1184574e474bca209dd2d/pyscriptjs/src/components/pyrepl.ts#L81-L86 to not have a fixed id but to have one that supports more than one instance.

**Comment by antocuni** [comment]
After merging #884, the code snippet about is outdated. The updated one is this:
https://github.com/pyscript/pyscript/blob/214e39537bf18e1bec65153fdaa2fce355999693/pyscriptjs/src/components/pyrepl.ts#L95-L110

We assign the id `code-editor`, and the only purpose is to use it for the `for` attribute of the `label`.
Also note that the label is not really displayed, but it's there just for screenreaders:
https://github.com/pyscript/pyscript/blob/214e39537bf18e1bec65153fdaa2fce355999693/pyscriptjs/src/components/pyrepl.ts#L120-L130

And we have the same problem for `runButton`:
https://github.com/pyscript/pyscript/blob/214e39537bf18e1bec65153fdaa2fce355999693/pyscriptjs/src/components/pyrepl.ts#L132-L134

I think that the best solution would be to avoid IDs altogether for these two cases.
This [StackOverflow answer](https://stackoverflow.com/a/8537641) suggests to use implicit label association, e.g.:
```html
<label><input type=checkbox name=chkbx1> Label here</label>
```

**Comment by fpliger** [comment]
Thanks for pointing it out.

I think the main issue is less about the `label`s and more about the static constant value of `id`. I mean, I get your point that, from a local code standpoint, that's why we need it but, in general, we need it to identify the component (if users want to interact with it somehow).

Now that I'm thinking a bit more about it, we can skip the problem and only assign an id if it's not passed as attribute in the component. If there are > 1 `py-repl` in the page and none of them have an `id` we raise an error saying that at least one of them needs `id`, and we avoid generating uids.

**Comment by antocuni** [comment]
> Thanks for pointing it out.
> 
> I think the main issue is less about the `label`s and more about the static constant value of `id`. I mean, I get your point that, from a local code standpoint, that's why we need it but, in general, we need it to identify the component (if users want to interact with it somehow).

to be honest I never really understood why we feel the need of putting IDs everywhere. If the user needs to interact with a tag that they wrote, they will assign it an explicit ID.
If we assign a random ID, the user cannot interact with it anyway because they don't know the name.

I think that @tedpatrick is with me here, but maybe I am missing something.

> Now that I'm thinking a bit more about it, we can skip the problem and only assign an id if it's not passed as attribute in the component. If there are > 1 `py-repl` in the page and none of them have an `id` we raise an error saying that at least one of them needs `id`, and we avoid generating uids.

or we write things more properly and avoid requiring the ID 😅.
In normal HTML you can use as many `<p>` and `<h1>` as you like, you don't have to give them IDs. Why should `<py-repl>` be different?

Looking at the code, it seems to me that in this specific case the ID are needed for the autogen functionality, because it uses some complex logic to find "the parent pyrepl which generated me". But this should be solvable with a better design, for example:
1. the editor+buttons+output div+pyexec logic are contained in a `<py-cell>` (or equivalent name)
2. a `<py-repl>` is a sequence of `<py-cell>` (also in the DOM, i.e. `PyRepl.childNodes() === [PyCell(), PyCell(), PyCell(), ...]`)
3. when you execute a `<py-cell>`, you append a new child to the parent PyRepl.

This way you no longer needs `exec-id` and `root`, and then you no longer need the ID of the pyrepl.

**Comment by JeffersGlass** [comment]
Is this still an issue since #912 was merged?

**Comment by marimeireles** [comment]
No, this works well now :)
