### ISSUE TITLE
Allow to turn off debug mode

### ISSUE THREAD

**Issue by lwcorp** [pyscript/pyscript#901]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

When loading PyScript the browser's console is full of related messages.
How about a a way in `<py-config>` not to show them?

![image](https://user-images.githubusercontent.com/1773306/198739547-f4eb814b-8db9-406a-ae81-bd5c1d9ee905.png)

### Why is this needed

While those messages are awesome for debugging, they're very bad for production.

### What should happen?

Add an option in `<py-config>` of debug: false and also consider making it the default.

**Comment by antocuni** [comment]
> While those messages are awesome for debugging, they're very bad for production.

I'm not an expert of Web Development so this might be a dumb question but: why they are bad for production? The vast majority of users don't look at the console at all, so does it make any difference?

 > Add an option in of debug: false and also consider making it the default.

- +1 for adding an option for configuring the log level

- -1 for calling it `debug = off`; instead, we could add a way to configure the default log level, e.g. `logging_level = 'info' | 'log' | 'warning' | etc.`, where `'info'` is the equivalent of what we have now

- -1 for turning off logging by default. One of the main group of users that we are targeting are "beginners", and I would like to have default which are as easy as possible for them, i.e. verbose logging by default, warnings and errors appearing in the DOM, etc.. Everything should be configurable so that "expert users" can turn them off, of course.

**Comment by lwcorp** [comment]
So I guess I believe the default should be `debugging_level = 'error'` which is what JavaScript does (unless you actively add console commands).

As for why not presenting debugging in production, it's just considered unprofessional. But I went ahead and found some sources for this (sorted by how persuasive I found them), plus I guess hackers might use that info against you:
1. [Remove console.log from Production Mode](https://dev.to/drsimplegraffiti/remove-consolelog-from-production-mode-4d8i)
1. [Is it good practice to leave debug.print or console.log in production phase?](https://www.quora.com/Is-it-good-practice-to-leave-debug-print-or-console-log-in-production-phase)
1. [Should I keep console statements in JavaScript application?](https://stackoverflow.com/questions/28190434/should-i-keep-console-statements-in-javascript-application)
1. [Deactivate console.log on production (Why and How)](https://medium.com/@hfally/deactivate-console-log-on-production-why-and-how-d0345abbe71)

**Comment by antocuni** [comment]
> So I guess I believe the default should be `debugging_level = 'error'` which is what JavaScript does (unless you actively add console commands).

the fact that JS does something doesn't mean that it's necessarily a good thing 😅.
Personally, I explained above why I think it's a good idea to enable verbose logging by default, at least for a certain category of users that we care about.
I'm happy to hear the opinions of other maintainers.



> As for why not presenting debugging in production, it's just considered unprofessional. But I went ahead and found some sources for this (sorted by how persuasive I found them), 
[cut]

thank you, these were interesting read. I guess I don't agree with many of the things which they say, but of course this doesn't mean that I'm right. It's always good to know what other people think.

> plus I guess hackers might sometime be able to use that info against you

not really. It's client side scripting, so it's relatively easy for a hacker to inject code to log everything they need. Removing `console.log` statements doesn't protect you from any attack (but it might make the hackers' life slightly simpler, yet)

**Comment by marimeireles** [comment]
+2 for adding an option for configuring the log level

>plus I guess hackers might sometime be able to use that info against you

-1

@antocuni we should have an easy way of offering the possibility to switch to users. But I do agree the majority of our users (the developers who consume pyscript) would prefer to have it by default. @lwcorp I agree with you if we look at this problem under the perspective of a webdev, as in, when I open some interactive website (say codepen) I don't see a wall of text of their logs. The thing is, I think this feature is very useful for a) everyone that's a beginner and just want to get going with pyscript b) scientists don't really tend to care about the "right way of developing software", they just want to get their research done and I believe they'd prefer to have this option turned on by default instead of fiddling with configuration.

We're always trying to think on an overarching way to accommodate the biggest amount of users possible, so that's why I tend to agree with Antonio here.

But that's my 2 cents, happy to hear counter arguments.
Cheers and thanks for opening up this issue here!

**Comment by FabioRosado** [comment]
+3 for adding an option for configuring log level

It also feels like the default logging is a good user experience for people that are starting using pyscript and want to know what's happening under the hood - it will also help us when trying to debug things 😄

**Comment by WebReflection** [comment]
as of today, we use `console.debug` for stuff we feel like relevant when devtools is already opened, but those logs are nowhere when devtools opens all of a sudden.

Our interpreters (Pyodide and MicroPython) might do the same for their own related internal logic, and it's not possible for us to fix those unless we override native devtools `console` and purpose.

As such is the current state, I think this issue can be closed.

**Comment by lwcorp** [comment]
Thanks!!! Did you end up allowing to modify that behavior in `<py-config>`?

Also, although `console.debug` is shown just in the browser devtools' console's Verbose mode, why is needed to expose in production that pyscript is used?
![image](https://github.com/pyscript/pyscript/assets/1773306/7ce70d78-154a-49d5-a70a-f8d0ab1d0cc5)
