### ISSUE TITLE
PyScript always produces a console warning

### ISSUE THREAD

**Issue by lwcorp** [pyscript/pyscript#902]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

Even if a webpage has nothing but PyScript's basic installation (CSS and JS), the browser's console always shows a warning about [pyodide.js.map](https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.js.map) (which is indeed a dead link):

![image](https://user-images.githubusercontent.com/1773306/198739822-7526718a-f05b-4c9b-9eaf-891528c35260.png)

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/pyodide/v0.21.2/full/pyodide.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by JeffersGlass** [comment]
Thanks for the issue submission! This error is due to a bug in Pyodide 0.21.2 (the default runtime for PyScript 2022.09.1), where source maps were not included with the distribution.

The next release of PyScript (and current unstable builds) [default to Pyodide 0.21.3](https://github.com/pyscript/pyscript/pull/887) (or higher) which [fixed the issue](https://github.com/pyodide/pyodide/pull/3088).

As this is a solved-issue as far as the codebase is concerned, I’d like to close this issue out - the improvement will be visible in the next release build, or right now in unstable or locally-built versions.

**Comment by antocuni** [comment]
yes, it seems to be a "bug" of pyodide which has already been fixed, and there is not much that we can do on your side anyway. Closing it but thank you @lwcorp for reporting it!
