### ISSUE TITLE
[Discussion] Where should the dev docs live?

### ISSUE THREAD

**Issue by FabioRosado** [pyscript/pyscript#907]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

We touched briefly on the subject of creating dev docs while talking in #897. Perhaps the discussion will be pretty short, but it may be good to open this issue for tracking.

The idea of creating a home for the dev docs, is so we can document things such as deprecation cycles and such. It may also help trim the contributing doc (or move it all). 

Do you think the dev docs should live in the documentation under a `development` category, or should we use the wiki for it?

I'm inclined to say that it should live in our docs, mainly because it's a single place  but also because we used to use Gitlab's wiki and the discoverability of articles was pretty terrible (although GitHub seems to be a bit better at that)

**Comment by antocuni** [comment]
+1 for having development docs. For example I wanted to write down some docs about all the custom pytest options which I introduced, but I never did since I couldn't find an obvious place for them (and I was too lazy to create one 😅).

+1 for having it as a section of the main docs: it because much easier to keep them in sync with the codebase, and they have more visibility.

**Comment by JeffersGlass** [comment]
> +1 for having it as a section of the main docs: it because much easier to keep them in sync with the codebase, and they have more visibility.

+ 1 from me as well.
