### ISSUE TITLE
Add Sphinx docs for discoverability on RTD

### ISSUE THREAD

**Issue by willingc** [pyscript/pyscript#98]
Let's consider adding sphinx docs using myst on RTD so Pythonistas can more easily discover information.

**Comment by fpliger** [comment]
@jezdez Not sure if there's any status update on this since all the docs infra automation.

**Comment by marimeireles** [comment]
The "pyscript" name is taken in RTD: https://readthedocs.org/projects/pyscript/ by a project that doesn't really exist yet.

**Comment by jezdez** [comment]
@marimeireles Sorry I have missed @fpliger's question above. To answer it:

We did eventually go with Sphinx and MyST (https://docs.pyscript.net/) but decided against using Read The Docs because it would make seeing docs build errors harder for contributors and the integration in the rest of our GitHub Actions CI setup much easier. I'm uncertain if these assumptions are still true, I haven't been involved with pyscript since then.

I do worry a little of assigning this a https://github.com/pyscript/pyscript/labels/good%20first%20issue, given the infrastructure perspective of it.

**Comment by marimeireles** [comment]
Uhum.
Well, I personally don't think people are searching for docs directly on RTD. I think if people are looking for pyscript docs they'll either go to the website or here or type "pyscript docs" in google.
But maybe I'm missing out on something Carol knows? @willingc 

And fair enough, I thought we were settled in having docs there, I'll remove the tag and possibly close the issue if we all converge towards it's not relevant anymore.

**Comment by willingc** [comment]
All good @marimeireles. I prefer hosting on RTD when it makes sense. It's fine to keep as currently implemented. 

@jezdez Good point about the tooling not being a good first issue.

Closing 🌻
