### ISSUE TITLE
[RELEASE BLOCKER] Clean up the `PyScript` vs `pyscript` mess

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#986]
There is a lot of confusion about using `pyscript.XXX` vs `PyScript.XXX`. Related PR #982 .

Let's start from the current state in github main. We have this:
https://github.com/pyscript/pyscript/blob/a6280268383d92fe180f32b500a7829aeac7f877/pyscriptjs/src/python/pyscript.py#L121-L172

and this:
https://github.com/pyscript/pyscript/blob/a6280268383d92fe180f32b500a7829aeac7f877/pyscriptjs/src/python/pyscript.py#L465-L466

Remember that currently the content of `pyscript.py` is merely executed in the global namespace, so all names defined there are automatically available to the `<py-script>` tags.

Let's ignore `set_version_info` for now. The class `PyScript` exposes a bunch of static methods and the `loop` variable; `pyscript` is an instance of `PyScript`: since they are static methods, the two following lines are essentially the same:
```python
pyscript.write(...)
PyScript.write(...)

pyscript.loop
PyScript.loop

#...
```

`set_version_info` is weird: it is a class method which destroy itself upon calling. It is called from here:
https://github.com/pyscript/pyscript/blob/a6280268383d92fe180f32b500a7829aeac7f877/pyscriptjs/src/pyodide.ts#L73-L75

What it does is to compute and attach `version_info` to the `PyScript` class, which means that it will be available both as `PyScript.version_info` and `pyscript.version_info.`

---

Things will become even weirder as soon as #961 is merged. In that PR, `pyscript` becomes a real module. And by default we do `from pyscript import *` in the global namespace:
https://github.com/pyscript/pyscript/blob/764f01ce30112e4794f598448ebf12d90a531f3b/pyscriptjs/src/main.ts#L217-L224

So, the end result is that in that branch, we have the following:
```python
 # both should work. Note that pyscript is NOT the pyscript module, but the PyScript() instance!
PyScript.write(...)
pyscript.write(...)

import pyscript
# now we imported the pyscript module, and we shadowed the previous pyscript variable
pyscript.write(...) # AttributeError
PyScript.write(...) # works
pyscript.pyscript.write(...) # works
pyscript.PyScript.write(...) # works
```

Honestly, it's a giant mess and it's extremely confusing. Especially the fact that `pyscript` is always available but contains different things if you do or don't do the `import pyscript.`.
I think this is enough to be a release blocker IMHO.

---
**Solution**

I propose the following:
1. kill the `PyScript` class: its static methods will become top-level functions of the `pyscript` module. The same for `loop` (if we really want to expose it)
2. same for `set_version_info` (which should probably be renamed to `_set_version_info`. It should set a `version_info` attribute on pyscript module.
3. kill the `pyscript = PyScript()` instance
4. remove the `from pyscript import *`, and instead do a proper `import pyscript` automatically in the global namespace
5. do the equivalent of `from pyscript import display`, to make sure that `display()` is always available

This plan has the nice property of cleaning up a bit of mess (the useless `PyScript` class) and automatically preserve some backwards compatibility (because e.g. `pyscript.write()` continues to work: instead of being a staticmehod on the `pyscript` instance, it's a normal function on the `pyscript` module.

With this setup, we have the problem of breaking some other backwards compatibility though: in particular, the various `Element`, `document`, `micropip`, and `PyScript` are no longer available in the global scope. I propose to fix this using the solution which I described in this comment:
https://github.com/pyscript/pyscript/pull/961#discussion_r1032163076

**Comment by ntoll** [comment]
@antocuni blimey.

Thoughts (that mostly resonate with your proposed changes).

* Why are we using static methods (do we do something special with the class)..? Otherwise, they should just be plain old functions, right..? Nice and simple and easy to understand.
* `set_version_info` feels bonkers. Why not just `const version = "1.2.3";` somewhere obvious as a single point of reference..?
* I'm really a fan of new-style JS classes. Damn kids, get off my lawn. What's wrong with a function defining a closure and returning plain old JS object containing methods and const values..?

**Comment by antocuni** [comment]
> * Why are we using static methods (do we do something special with the class)..? Otherwise, they should just be plain old functions, right..? Nice and simple and easy to understand.

I don't know, this code predates me. I guess that the original idea was to offer a `PyScript` namespace where to put various stuff, but I don't really know.
Anyway, AFAIK we don't do anything special with the class so we can just kill it.

> * `set_version_info` feels bonkers. Why not just `const version = "1.2.3";` somewhere obvious as a single point of reference..?

We have a single point of reference, but it's in JS:
https://github.com/pyscript/pyscript/blob/764f01ce30112e4794f598448ebf12d90a531f3b/pyscriptjs/src/runtime.ts#L7-L9

`set_version_info` is used to make it available also on the Python side. It seems a bit overengineered though.

> * I'm not really a fan of new-style JS classes. Damn kids, get off my lawn. What's wrong with a function defining a closure and returning plain old JS object containing methods and const values..?

in which way this is related to this issue? :thinking:

**Comment by ntoll** [comment]
> in which way this is related to this issue? thinking

My misunderstanding, and I must be getting grumpy in my old age. :-)

**Comment by JeffersGlass** [comment]
Just to clear something up - what @FabioRosado and I are discussing in #982 is unrelated to object naming in Python. It's about the JS module.

In #868 I had elected to name the exported _javascript_ module "pyscript", as in `pyscript.runtime.interpreter.runPython("1+2")`.  In a couple of the examples, I had erroneously left it as "PyScript" - I could not find a consistent naming convention (CamelCase vs. lowercase vs. Capitalized) for naming js modules, so I elected to use lowercase. But like I say, that's in JavaScript, is set in `rollup.config.js` and is unrelated to this issue.

----

I completely agree that the `pyscript` instance vs `PyScript` class thing is a mess, and we should fix it. Steps 1 through 5 seem sound (with one exception, see next) +5 on renaming to `_set_version_info()` creating a version_info and __version_info___ attribute on the module.

One challenge in moving from running pyscript.py in the global namespace to importing a module (+5 yes please) is that we've been importing certain modules into the global namespace "for the user" by importing them at the top of pyscript.py, including: ast, asyncio, base64, html, io, and time. So users can have been writing:

```
<py-script>
now = time.localtime()
print(now)
</py-script>
```

This is bad and should not have been possible, but the point is it _has_ been possible, and if we're going to take that ability away, it would be nice to have a deprecation warning for it too.

I guess my desire would be to have deprecation warnings/error for all the objects that have been available in PyScript.py, since we don't know which ones users may have been using. In 2022.09.1, that list was:

> Element', 'HTML', 'MIME_METHODS', 'MIME_RENDERERS', 'PyItemTemplate', 'PyListTemplate', 'PyScript', 'PyWidgetTheme', 'TopLevelAsyncFinder', 'add_classes', 'ast', 'asyncio', 'base64', 'create', 'dedent', 'display', 'eval_formatter', 'format_mime', 'get_current_display_target', 'html', 'identity', 'io', 'loop', 'namedtuple', 'pyscript', 'render_image', 'set_current_display_target', 'time', 'uses_top_level_await'

Like it or not, that's been the accessible surface of the PyScript API to this point. And if we're going to change that, we should try to deprecate the unavailable 

I don't know what's best to handle long-dead things like OutputCtxManager. It would be nice if users trying to access it got a NameError (or similar) that actually explained that those objects are gone.

**Comment by JeffersGlass** [comment]
On reflection, maybe I'm being too precious about the state of the API - especially with modules, users can figure out they need to import their own modules, presumably.

**Comment by antocuni** [comment]
With the `DeprecatedGlobal` approach which I described above, we can easily add as many names as we want.
Not sure if it's a good idea to use it for *all* the names which you mentioned, but if we want we wan

**Comment by JeffersGlass** [comment]
> Not sure if it's a good idea to use it for all the names which you mentioned, but if we want we want.

Agreed. deprecating every single name is overkill - it's a fault of mine, I get nervous around big user-facing API changes without properly deprecating every last little thing 😅. But with warnings along the lines you propose, this hopefully will be the last time we have such a massive change all in one fell swoop.

**Comment by fpliger** [comment]
I'm +1 on all the proposal, except of 4. I'm quite committed to trying to give a deprecation cycle between changes/releases and `4` would be basically a way to see, "meh, we don't care this time". As @JeffersGlass mentioned, there are lots of walking dead code in there that we should remove (and I'd be ok to just remove without warning) but they are mixed with things that are part of the current API. We are talking about 1 month (actually we can release early in December if we want to accelerate the rest) and I don't see a good reason for not sticking with deprecating and removing later.


> Why are we using static methods (do we do something special with the class)..? Otherwise, they should just be plain old functions, right..? Nice and simple and easy to understand.

This was a bad ugly hack for the wrong reason and ended up remaining there. Simple as that :)

**Comment by fpliger** [comment]
Also, there's another aspect of this that I want to make explicit (and that @antocuni and I definitely disagree). The vision of PyScript is **not** that PyScript == Python. PyScript is a platform where Python is at the center of gravity but its main goal is not [only] to enable Python on the Browser but to bring programming to the masses, on the browser. If there are things that add value and make programming easier and more fun, we should most definitely add them to the global namespace, even if "it's not Python" (because the goal here is not to be Python!). Supporting MicroPython "will not be Python"! Adding other languages and trying to make them interop will not be Python. 

When choosing what is "correct" and what is best for our users (== what our users need), we want to prioritize the latter. (Obviously not all things are absolutes and there are lots of nuances but that is the vision with which we created the project ).

The reason we are removing everything from the global namespace (and leaving only `display`), is not because "it needs to be == Python" but because we want to be intentional and careful when adding things to the default global namespace.

**Comment by antocuni** [comment]
> I'm +1 on all the proposal, except of 4. I'm quite committed to trying to give a deprecation cycle between changes/releases and `4` would be basically a way to see, "meh, we don't care this time".

I'm confused. I never proposed to break backwards compatibility. I proposed to use `DeprecatedGlobal` which raises a warning only if you actually use a name.


> The reason we are removing everything from the global namespace (and leaving only `display`), is not because "it needs to be == Python" but because we want to be intentional and careful when adding things to the default global namespace.

I completely agree with this, I don't know why you think we are in disagreement here 😅.
When talking about pyscript design choices, I never said `if it's different that normal python it's bad`; usually when we disagree is because I think that that specific feature is bad per se.
