### ISSUE TITLE
We have two tests numbered as 03

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#995]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

https://github.com/pyscript/pyscript/blob/main/pyscriptjs/tests/integration/test_03_async.py
https://github.com/pyscript/pyscript/blob/main/pyscriptjs/tests/integration/test_03_style.py

Should be 3, 4. Not sure what's the best order?

**Comment by madhur-tandon** [comment]
Tagging @antocuni here

**Comment by antocuni** [comment]
yes, I think that the proper question which we want to answer is "which test files we want to number and why"?
My original reasoning was the following:
1. pytest collect `test_*.py` files in alphabetical order
2. sometimes it happens that you break a very basic functionality which in turns break all the tests
3. if (2) happen, I want tests to fail as fast as possible and to show "the most basic tests" first, so that it's easier to understand what's going on
4. `test_00_support.py` must be the very first because it tests the testing machinery itself: if it fails, there is no point in running further tests
5. `test_01_basic.py` must be the 2nd because it tests very basic features (such as the ability of running py-script tags) which are used by all the others
6. same for `test_02_output.py`, since it also tests functionalities used by all subsequent tests
7. `test_zz_examples.py` must be the last because you want to run them only if all the other tests passed

Apart for these, all the other tests don't have a "natural order" IMHO, so they should just not have numbers. I so propose to:
1. rename `test_03_async.py` ==> `test_async.py`
2. rename `test_03_style.py` ==> `test_style.py`
3. rename `test_04_runtime.py` ==> `test_runtime.py`

While we are at it, also rename `test_02_output.py` into `test_02_display.py`, because this is what it does: it tests the `display()` function

**Comment by marimeireles** [comment]
>While we are at it, also rename test_02_output.py into test_02_display.py, because this is what it does: it tests the display() function

Yes.

Following your line of thought of things should ideally only be ran once they're tested, I think it makes sense to have:

test_03_async.py ==> test_03_async.py
rename test_03_style.py ==> test_04_style.py

Because `async` is also a very elementary computation that is going to be used in several tests afterwards... So will style.

**Comment by antocuni** [comment]
well, not really. aync is not used by any other test, and test_style is basically testing some CSS rules which are surely not "fundamental".
As I said, trying to come up with the "perfect order" is basically impossible (if you start looking inside the tests, you quickly realize that they probably have cross dependencies). So, it's probably a good idea to keep only the very basic stuff (00_support, 01_basic and 02_display) and stop bothering about the rest

**Comment by madhur-tandon** [comment]
Assigning myself

**Comment by marimeireles** [comment]
Yeah, I know they do.
Alright, I have no strong feelings about it.
+1ing Antonio here.
